### PR TITLE
Add permission checks before saving image

### LINKED ISSUE #941: Android: download image from post raises low-level android error rather than grant permission dialog
**Describe the bug**

**To Reproduce**

1. From a post with an attached photo
2. Click the photo to view
3. Click 'Save' on the bottom menu of the photo view

**Expected behavior**

Expected: if appropriate permissions for saving files are not already granted to Blue Sky app, prompt for appropriate app permissions
using a standard Android dialog, or an in-app proxy for it. If granted, save the file [prompting for location].  If rejected, fail to save and continue.
 
Actual: Low-level error "Expo.MediaLibrary.createAssetAsync has been rejected", file is not saved.

**Screenshots**
Screenshot_20230702-074134

**Details**

 - Platform: Android
 - Platform version: 13
 - App version: Build version 1.37.0 (23) production

**Additional context**

### PR DESCRIPTION
**Pull request by ansh**
Fixes #941

### CODE REVIEW

**Comment by pfrazee** [comment]
Okay so -- this does work as intended, except if you do "Select photos" instead of all photos on iOS then it just fails permanently.

I wonder if there's a way to change our usage so that fewer permissions are needed or something.

**Comment by pfrazee** [comment]
Actually yes -- it looks like all the album stuff might be totally unnecessary and we just need to call `MediaLibrary.createAssetAsync(imagePath)`. It won't save to a specific album but it does save to the photo roll. (And that's actually a good thing because right now it's doing a copy into the bluesky album so it's double saving -- a separate issue.)

**Comment by pfrazee** [comment]
Testing on iOS and Android. If that's right I'll open a separate PR to supersede this one

**Comment by ansh** [comment]
I thought you wanted to do the Bluesky album thing. But yeah, if its not required, then its good.

**Comment by pfrazee** [comment]
Oh I def did but if it makes this harder, meh

**Comment by pfrazee** [comment]
Okay tested on android and ios from fresh devices, all set

**Review by pfrazee — APPROVED** [review]

**Pull request merged**
