### PR TITLE
Updates to use dynamic/responsive styles on web

### PR DESCRIPTION
**Pull request by pfrazee**
This bear of a PR switches us to using dynamic breakpoint hooks, adds tablet-sized layouts, and fixes up a couple of standing issues with layouts.

Tablet views:

CleanShot 2023-08-31 at 16 20 03@2xCleanShot 2023-08-31 at 16 20 30@2xCleanShot 2023-08-31 at 16 20 14@2x

### CODE REVIEW

**Comment by ansh** [comment]
CleanShot 2023-08-31 at 17 03 09@2x
Mobile profile top left button is back instead of the drawer opener button

**Comment by ansh** [comment]
Color differences in moderation screen  in tablet/desktop vs. mobile
CleanShot 2023
<img width=
-08-31 at 17 07 32@2x" src="https://github.com/bluesky-social/social-app/assets/8207733/6c4233e0-fc9d-47b2-acba-beedcb9730fa">

**Comment by ansh** [comment]
Spacing issue in discover feeds screen on desktop/tablet

CleanShot 2023-08-31 at 17 08 51@2x

**Comment by ansh** [comment]
Double discover feeds button on iOS 
CleanShot 2023-08-31 at 17 15 54@2x

**Comment by ansh** [comment]
Every time a post is opened, there is some wierd whitespace on top (iOS)

https://github.com/bluesky-social/social-app/assets/8207733/b6fe28f0-00cc-40ea-bd48-140fe2288771

**Review by ansh — APPROVED** [review]
Looks good. Some super small issues spotted that have been dropped as comments.

**Review by estrattonbailey — APPROVED** [review]
Looks so much better than it did! Nice one 👍

**Comment by pfrazee** [comment]
> Mobile profile top left button is back instead of the drawer opener button

That's a standing issue. The web navigation stack works differently than mobile so the tooling to do this isn't present. I'm going to leave it for now.

> Color differences in moderation screen in tablet/desktop vs. mobile

Actually the intended behavior

> Spacing issue in discover feeds screen on desktop/tablet

Fixed

> Double discover feeds button on iOS

Fixed

> Every time a post reply is opened, there is some wierd whitespace on top (iOS)

Gonna hit this in a followup PR -- the expo update adds some new facilities here

**Pull request merged**
