### PR TITLE
Migrate to Lytic 

### PR DESCRIPTION
**Pull request by ansh**
Thanks to @Jacob2161

### CODE REVIEW

**Review by estrattonbailey — APPROVED** [review]
Tight

**Comment by pfrazee** [comment]
Good to merge whenever

**Comment by Jacob2161** [comment]
Not quite ready to switch over yet. I need to make a couple small changes first (to unroll the batch mobile SDK API).

**Comment by ansh** [comment]
@Jacob2161 I am merging this then!

**Pull request merged**
