### PR TITLE
UX: account deletion dialogue does not tell me which account I'm deleting

### PR DESCRIPTION
**Pull request by gitstart**
Fixes https://github.com/bluesky-social/social-app/issues/834
### web example
web1
image2

### mobile example
mobile1
mobile2

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by ansh** [comment]
The screenshots are broken on this PR, any chance you could try re-uploading them?

**Comment by gitstart** [comment]
> The screenshots are broken on this PR, any chance you could try re-uploading them?

Screenshots should be visible now.

**Comment by ansh** [comment]
Thanks for opening this PR! Just checked this out. Direction is good and correct however a few changes that will be required before merging:
- Background of whole modal should be same color, right now its half white and half grey
- Overflowing text is not handled properly
- We should always just show the handle rather than the display name since that is more accurate

CleanShot 2023-06-06 at 18 39 20@2x

**Review by ansh — APPROVED** [review]
Thanks for making the changes, this looks good!

**Pull request merged**
