### PR TITLE
Update Korean localization

### PR DESCRIPTION
**Pull request by quiple**
I've localized the added strings. It would be great to merge it when the next release comes out!

I'll keep updating this PR as additional strings become available.

### CODE REVIEW

**Comment by quiple** [comment]
I updated for the added strings.

**Comment by hurss** [comment]
I have update a little translation text from https://github.com/quiple/social-app/tree/update-korean-localization. My repository is https://github.com/hurss/social-app/tree/korean-localization if you want to update Korean translation.

**Comment by quiple** [comment]
> I have update a little translation text from https://github.com/quiple/social-app/tree/update-korean-localization. My repository is https://github.com/hurss/social-app/tree/korean-localization if you want to update Korean translation.

Thank you! I double-checked the string in that part against your localization and updated the localization.

**Comment by quiple** [comment]
I would like #2537 to be merged first before merging this.

**Comment by pfrazee** [comment]
@quiple okay that's merged. I assume you want to tune something here in response, then this is ready to go?

**Comment by quiple** [comment]
> @quiple okay that's merged. I assume you want to tune something here in response, then this is ready to go?

@pfrazee I found one more part of the translation where the position of `Trans` needed to be changed. #2568

I've updated the Korean localization. Please merge the above PR and I'll update again.

**Comment by quiple** [comment]
@pfrazee I don't think there's any problem with modifying it now, thanks!

**Comment by quiple** [comment]
@pfrazee Please merge #2502 as well, and I'll update localization again.

**Comment by pfrazee** [comment]
@quiple okay done -- lmk when this is good to go

**Comment by quiple** [comment]
@pfrazee Yeap, I think It's done, thanks!

**Review by pfrazee — APPROVED** [review]
Wonderful, thank you! Merging!

**Pull request merged**
