### PR TITLE
Updated fr locale and added fr_CA locale

### PR DESCRIPTION
**Pull request by lra**
This is an attempt to solve the issue where some people want to use gender-neutral french, and others prefer to use academic french, by giving everyone the choice to pick their locale.

Summary of the changes:

- Forked the `fr` locale to `fr_CA` to both follow the request to keep it gender-neutral in https://github.com/bluesky-social/social-app/issues/2425 for the `fr_CA` locale, and at the same time, follow the [french academic rules](https://www.academie-francaise.fr/actualites/declaration-de-lacademie-francaise-sur-lecriture-dite-inclusive).
- Updated both `fr` and `fr_CA` from the source code
- Removed `fr_CA` specific punctuation that should not be applied for `fr`.
- Removed orphaned translations
- Added 136 new translations to both `fr` and `fr_CA` (using gender neutral language for continuity) to reach 100% completion on both locales
- Fixed some existing translations (bad white space characters, redundant punctuation, ...)
- Keep the previous translation team choices on terms harder to translate, e.g. "post", pseudo", "fil de discussion", ...

This will give the choice for anyone to use the locale they want.

Thanks.

### CODE REVIEW

**Comment by lra** [comment]
> This pull request would be very hard to review anyway, as you only offer one commit that does a lot: bumping locale strings in fr, removing gender neutral forms that uses point médian in fr, and indeed creating the fr-ca locale.

You can see the main diff in `src/locale/locales/fr/messages.po`, the other file has only a few diffs with the main one.

> This pull request is removing non-breaking spaces in the fr locale, but those are mandated by the typographic rules commonly used in French written in France (see: Lexique des règles typographiques en usage à l'Imprimerie nationale (2002), p. 147-149). Of course, it's not only a matter of some authority source — those are actually followed by most UI software translations.

TIL, I'll bring them back, thanks: https://github.com/bluesky-social/social-app/pull/6570/commits/7ce96de405afa7575166824054b8f4074a09617c

> This pull request is keeping spaces before some punctuations (like :, ! or ?) when there should not be any, according to the [Vitrine Linguistique of the Office québcquois de la langue française](https://vitrinelinguistique.oqlf.gouv.qc.ca/22039/la-typographie/espacement/espacement-avant-et-apres-les-signes-de-ponctuation-et-les-symboles). Again, not a matter of authority, it's just the main difference between fr-fr and fr-ca in other softwares too.

Thanks, I'll include those changes: https://github.com/bluesky-social/social-app/pull/6570/commits/7ce96de405afa7575166824054b8f4074a09617c

Again, my intentions are to try to make the platform as welcoming as possible, giving the option for anyone to use what they prefer, locally.

**Comment by lra** [comment]
Bringing the translation up to date to 100% is not "no work". I don't know the rules for regarding gender-neutral french, so I added the new translated locales the way everything else was translated.

Your are free to PR this PR, or to PR later on `main` to improve this.

> i don't see how splitting french in two benefits anyone

It benefits the platform, being more welcoming for anyone that's more comfortable reading french.

**Comment by Guillawme** [comment]
I saw a link to this PR on Mastodon and just wanted to drop by to say: you might not want to blindly rely on the Académie française's dictionary, and exercise some critical thinking about it first.

Why? you ask. For example because its latest edition added the word ["négroïde"](https://www.dictionnaire-academie.fr/article/A9N0244) without any mention of its racist origin and meaning. This is not an old entry simply being neglected or forgotten and not updated: this word is not present in the 1935 edition nor any of the older ones.
This is not the only such example, more info here: https://social.sciences.re/@tract_linguistes/113511025814431129

If this isn't enough reason to distance yourself from this dictionary, I don't know what is.

This collective holds more reasonable views on today's French language: https://www.tract-linguistes.org

(In case this is relevant: I am a French native speaker.)

**Comment by eevee** [comment]
> It benefits the platform, being more welcoming for anyone that's more comfortable reading french.

i suspect this is already obvious to anyone reading, but: it is deeply cynical and distasteful to frame this as some magnanimous attempt to be "more welcoming", when the only person you've shown to have an issue is _you_, and the thing you have an issue with is an existing attempt to be more inclusive of _other people_.

**Comment by lra** [comment]
It's not a debate about the legitimacy or not of this language, GitHub is not the place for it and nobody is going to solve it here, there are plenty of statements showing it is a divisive subject, e.g. [the french government banned it from official documents](https://kiosque.bercy.gouv.fr/alyas/msite/view/vigie/11263).

This is about giving the users the choice to pick the locale they want, and not forcing it on them one way or another.

This PR is not removing anything to anyone, but adding the choice in a local setting.

**Comment by lra** [comment]
> @lra I apologize, but you are selectively quoting official notes. A few years later, the French government also emphasized inclusiveness as one of the three primary principles in addressing the public.
> 
> https://www.info.gouv.fr/marque-de-letat/comment-s-adresser-aux-citoyens#inclusion

Everybody is. That's not the point of this PR.

**Comment by taniki** [comment]
Additionally, I would like to highlight an article published in 2011 by the former executive director of Wikimedia Foundation on the negative impact of exclusionary language:

> 8) Some women whose primary language has grammatical gender find being addressed by Wikipedia as male off-putting.

**Comment by meow10811** [comment]
It frankly doesn’t seem like you’ve done that much research into actually making this a proper `fr_CA` localization — for instance, I would expect “[courriel](https://vitrinelinguistique.oqlf.gouv.qc.ca/fiche-gdt/fiche/8353974/courriel)” (which is common even in casual speech in Québec) to be used in place of “e-mail”, at the bare minimum.

Given the context of your previous issue, this doesn’t seem like a genuine attempt to provide a Canadian French localization.

**Comment by lra** [comment]
Fixed, thanks: https://github.com/bluesky-social/social-app/pull/6570/commits/198b51d05f78e1aa6c6ef1a95ae86df9a0b38958

**Comment by tchoutri** [comment]
@lra Your PR is full of Frenchisms that Canadian speakers (who are not all Québecois, New-Brunswick is also Francophone), do not use. Please do your homework when you try to weaponise Canadian francophones for your weird little crusade, if you must.

**Comment by zopieux** [comment]
Since the Bluesky maintainers are not expected to have background context on French institutions & history, and to complement Guillawme's point above, I'll point out that the *Académie française*, which the PR author loves to quote as an "academic" reference and de facto source for the correct use of French, is self-declared as the official ruler of some abstract "correct use" of French, but is in no way recognized as such by French people and ofc even less so by other French speaking cultures. In fact, it is often mocked for its out-of-touch, arbitrary rulings. The institution promotes a prescriptive understanding of the language, which clashes with the descriptive nature of a linguist' job: capturing the language as it is employed by its current speakers, not as it _should be_ per some abstract and arbitrary standard which, in *Académie française*'s case, is deeply rooted in [elitism and conservatism](https://en.wikipedia.org/wiki/Acad%C3%A9mie_Fran%C3%A7aise#Alleged_conservatism).

For context, it took the *Académie française* 345 years and some public outcry to finally let in its first female members, of which there are 6 out of 40 seats today. It still employs [zero linguists](https://www-lexpress-fr.translate.goog/culture/pourquoi-lacademie-francaise-ne-compte-t-elle-pas-de-linguiste-dans-ses-rangs-JP54OMRWVRFIDACOEIRZ7JU4GE/?_x_tr_sl=fr&_x_tr_tl=en&_x_tr_hl=en-US&_x_tr_pto=wapp) — you know, the people whose job it is to analyze and understand languages.

This PR is motivated by a personal crusade rather than an actual issue. The proposed changes are backed by highly controversial references and of dubious quality according to native Canadians. In fine, this will induce undue i18n maintainance load.

**Comment by dmathieu** [comment]
This issue is a ludicrous attempt from a fascist to maintain their antique view that men and women as unequal, and that the world needs to be patriarchal. It should be closed and restricted, like #6512 was.

**Comment by haileyok** [comment]
@Signez has been the maintainer of our French translation for some time. I will be deferring judgement to him as a result.

To be clear, it seems that at least some of the changes in this PR were rejected in https://github.com/bluesky-social/social-app/issues/2425 - albeit for the "official" French translation rather than the Canadian French translation. There are also additional French speakers who have responded to both of these PRs with their understandings of the situation. Based on those comments, and in an effort to maintain civility within the repo, I'll close this. If you wish to address the concerns stated by the various replies to this PR, you may open another one once you have done so.

**Pull request closed without merging**
