### PR TITLE
fix: expo-image build issue on ios 

### PR DESCRIPTION
**Pull request by matinzd**
Update expo-image to 1.2.3

Issue: https://github.com/expo/expo/pull/22491

### CODE REVIEW

**Comment by matinzd** [comment]
Ping

/cc @pfrazee

**Comment by thepudds** [comment]
Hi @matinzd 👋, just a brief drive-by comment that Paul has generally said "RIP my inbox" and that they are not going to be able respond quickly to all PRs... so I don't know if I'd ping ~7 hours after opening a PR.

(And sorry if this is off-base or if I'm missing context here -- there might in fact be a very good reason to ping this PR. I'm just a random but interested member of the community 😅 ).

**Comment by matinzd** [comment]
Since it's a very small PR and I saw him active on the main branch. :) I am not that familiar with the community yet as it is my first contribution. If that's the case, thanks for bringing it up.

**Comment by thepudds** [comment]
No worries! And my best guess is Paul will visit this PR before too long.

**Comment by parion** [comment]
This versioning drove me insane on initial setup. Gets my thumbs up 👍

**Review by pfrazee — APPROVED** [review]
Looks good! Thanks!

**Review by pfrazee — APPROVED** [review]
Looks good! Thanks!

**Comment by matinzd** [comment]
Is there any way I can an invite code to test the app or at least on staging server? 
I have been in the waitlist for a long time :) 

@thepudds @pfrazee

**Comment by matinzd** [comment]
> You don't need an invite code to test/contribute to the app. If you follow the [build instructions](https://github.com/bluesky-social/social-app/blob/main/docs/build.md), you should have an instance of ATProto running locally on your machine. When you load the app the first time, chose "Create a new account" and then, in the hosting provider panel, choose Other. There's an option for dev server which will auto-populate the local host address of ATProto. No invite code required!
> 
> image
> 
> 

I was thinking if running the server locally. But it would be awesome if I could just have access to staging server at least and not deal with keeping server updated :)

**Comment by parion** [comment]
Don't quote me, but I'm pretty sure that's internal to the dev team.

**Pull request merged**
