### PR TITLE
#437 Selectable Text [WIP]

### PR DESCRIPTION
**Pull request by ansh**
- Render TextInput if RichText is meant to be selectable

Known issues:
- Doesn't work with posts with links

### CODE REVIEW

**Comment by elboboua** [comment]
This seems like a known issue with expo + RN unfortunately. I was trying to get this working on my twitter clone last year to no avail.
Here's the issue in the RN repo itself: https://github.com/facebook/react-native/issues/13938

**Comment by matinzd** [comment]
Yes this is an issue related to RN specifically. I had a lot of issues in my integrations as well.

**Comment by ansh** [comment]
Yeah this is a known issue. I got really close but couldn't do anything about rich text within the post, which is annoying.

**Comment by pfrazee** [comment]
it's closed on RN as a wontfix, not as resolved

**Comment by elboboua** [comment]
FWIW @pfrazee  I have been able to essentially recreate rich text that is selectable by nesting the text in a WebView and writing custom html for the component I need. Having an auto-height adjusting webview makes this fit in well with any UI: https://github.com/iou90/react-native-autoheight-webview

**Comment by haileyok** [comment]
Closing this outdated PR in favor of https://github.com/bluesky-social/react-native-uitextview

**Pull request closed without merging**
