### PR TITLE
Translate moderation details with japanese text

### PR DESCRIPTION
**Pull request by haoyayoi**
Add translate moderation details. This pr po-translated-text contain japanese only.

Run with:
```
yarn intl:build
yarn intl:compile
```
スクリーンショット 2024-03-07 22 54 39

### CODE REVIEW

**Comment by tkusano** [comment]
moderation related messages marked translatable are included in [3p-moderators](https://github.com/bluesky-social/social-app/tree/3p-moderators) branch, so wait until the brach is merged into [main](https://github.com/bluesky-social/social-app/tree/main).

**Comment by haoyayoi** [comment]
updated from src/view/com/modals/report/ReasonOptions.tsx to src/lib/moderation/useReportOptions.ts

**Comment by tkusano** [comment]
The bluesky-social:3p-moderators branch has been merged into bluesky-social:main, and the number of translation targets has increased considerably.

A trial translation of the 3p-moderators branch has been placed at [my repository](https://github.com/tkusano/social-app/blob/l10n-3p-moderators/src/locale/locales/ja/messages.po) for your reference.

There are also people working on PR #3196 , so please collaborate with them.

**Comment by haoyayoi** [comment]
Close and re-up po PR, big diff fix so hard.

**Pull request closed without merging**
