### PR TITLE
Nepali Translation (divyaswormakai's reviewed & some changes) 

### PR DESCRIPTION
**Pull request by whoisanku**
I looked over the PR #6943 from @divyaswormakai , looks good on his side most of the things but added some additional changes to make it better on language side.

### CODE REVIEW

**Comment by surfdude29** [comment]
Perhaps @divyaswormakai could have a quick look at your changes in 939121929e87479fdda445d2bc2c5b36a3803416 to check he agrees with them?

**Review by divyaswormakai — COMMENTED** [review]
@surfdude29 I agree with the changes. 
@whoisanku  added few translations that were missing when building and updated a few ones which are also good.

#6943

**Comment by whoisanku** [comment]
Now looking forward on a @gaearon 's final review & merge hopefully! Everything seems great-

**Review by pfrazee — APPROVED** [review]
Sweet!

**Pull request merged**
