### PR TITLE
Update Node.js to 20.x in Dockerfile

### PR DESCRIPTION
**Pull request by trivikr**
Refs: https://bsky.app/profile/yagiznizipli.bsky.social/post/3l7yibgike52z

Node.js 18.x will be reaching end-of-life on 2025-04-30
https://github.com/nodejs/Release#release-schedule

This PR proactively attempts to upgrade to newer LTS version.

### CODE REVIEW

**Comment by trivikr** [comment]
I went through the CI failures, and had to update node version in `.nvmrc`

Done in [`f912ede` (#6099)](https://github.com/bluesky-social/social-app/pull/6099/commits/f912ede3d9093a60a6096e76038698aa809c2d1a)

**Comment by trivikr** [comment]
The linting job wasn't using the node version from `.nvmrc`

I updated it in [`f86634f` (#6099)](https://github.com/bluesky-social/social-app/pull/6099/commits/f86634fddf39c21c4349509ee6807eb92fe7508a)

**Comment by trivikr** [comment]
The CI is succeeding. Is this good to merge?

**Review by gaearon — APPROVED** [review]
lets try it

**Comment by trivikr** [comment]
Looks like Node.js 20.x had to be updated in `Dockerfile.embedr` too

I've posted a PR at https://github.com/bluesky-social/social-app/pull/6242

**Pull request merged**
