### PR TITLE
Update italian localization

### PR DESCRIPTION
**Pull request by crazycoder1999**
Fixed a couple of labels
Translated others

### CODE REVIEW

**Comment by crazycoder1999** [comment]
I saw now there was already a PR
https://github.com/bluesky-social/social-app/pull/6347
but it was not merged.. 
probably better to make one..
@surfdude29 I tag you here, because I saw you in other PR like this :)
how do you suggest to proceed? 
thx

**Comment by surfdude29** [comment]
@crazycoder1999 PR #6188 which updated the Italian localisation was merged and those updates will be in 1.94 when it's released soon.

I suggest that all updates are consolidated so that only one PR is open at a time for the Italian localisation, either this one or #6347 :)

cc: @Lucaterzo

**Comment by surfdude29** [comment]
I see #6477 has also now been opened to update the Italian localisation, perhaps you all could coordinate on one PR?

cc: @arestifop

**Comment by crazycoder1999** [comment]
@arestifop and @Lucaterzo contact me on @dega1999.bsky.social so we can coordinate for one PR

**Comment by surfdude29** [comment]
Also tagging @marcomaroni-github

**Comment by arestifop** [comment]
@surfdude29 i merged #6457 from @crazycoder1999 into my #6477, now we can merge with #6347 or use mine PR as base?
cc @Lucaterzo

**Comment by surfdude29** [comment]
> @surfdude29 i merged #6457 from @crazycoder1999 into my #6477, now we can merge with #6347 or use mine PR as base? cc @Lucaterzo

It's up to you all to coordinate, I just think it would make sense to have one open at a time, it makes it easier (including for the devs) and more likely to be merged :)

**Comment by crazycoder1999** [comment]
Well done @arestifop 
let's work on keeping one open.
I close this PR.

**Pull request closed without merging**
