### PR TITLE
Finnish translation update

### PR DESCRIPTION
**Pull request by jaoler**
Translated new strings (GIF's etc) and cleaned up deprecated ones. I'm native finnish speaker.

### CODE REVIEW

**Comment by mankami** [comment]
Looks good!

**Review by mankami — COMMENTED** [review]
Looks good

**Review by jylipaa — COMMENTED** [review]
Looks good from another native Finn's point of view too 👍

**Review by JoSimila — COMMENTED** [review]
No issues detected, ok to be merged.

**Comment by lapanti** [comment]
On line 3003 there are double quotes, when there should be singles, otherwise ok 😊

**Comment by jaoler** [comment]
> On line 3003 there are double quotes, when there should be singles, otherwise ok 😊

Thanks! Fixed.

**Review by pfrazee — APPROVED** [review]
Thanks so much everybody!

**Pull request merged**
