### PR TITLE
bring back kawaii mode

### PR DESCRIPTION
**Pull request by ovnanova**
i'm a kawaii girl in a formerly kawaii world and now i'm in shambles

### CODE REVIEW

**Comment by dianna-io** [comment]
load bearing feature tbqh

**Comment by ovnanova** [comment]
> load bearing feature tbqh

many are saying this

**Comment by coreh** [comment]
we need to bring it to mobile tbh

**Comment by ovnanova** [comment]
> we need to bring it to mobile tbh

iirc the mobile app inherited the web setting? i remember seeing it in my mobile app.

**Pull request closed without merging**
