### PR TITLE
Add bare minimum hashtags support

### PR DESCRIPTION
**Pull request by kisaragi-hiu**
> I agree, hashtag support would be very useful precisely for the reasons you point out. Support wouldn't have to be as [detailed or as complex](https://business.twitter.com/en/blog/how-to-create-and-use-hashtags.html) as it is on, say, Twitter, just the simplest functionality mentioned to start with. It really would be a valuable feature.
>
> _Originally posted by @Luke717 in https://github.com/bluesky-social/social-app/issues/848#issuecomment-1577855453_

As atproto/api already parses hashtags, this is as simple as hooking it up like link segments.

This is "bare minimum" because:

- ~~Opening hashtag "#foo" is actually just a search for "foo" right now to work around #2491.~~ I have removed this workaround now that https://github.com/bluesky-social/indigo/issues/578 has been addressed.
- There is no integration in the composer. This hasn't stopped people from using hashtags already, and can be added later.
- This change itself only had to hook things up - thank you for having already put the hashtag parsing in place.

https://github.com/bluesky-social/social-app/assets/11722318/b3775f8e-b60e-4c16-9042-3cd60d1ace31

<details>
<summary>Screen recording of previous version with hashtag workaround</summary>
<video src="https://github.com/bluesky-social/social-app/assets/11722318/21a1d462-8285-48ce-8605-3f33388c64aa" controls="controls" muted="muted" class="d-block rounded-bottom-2 border-top width-fit" style="max-height:640px; min-height: 200px">
  </video>
</details>

### CODE REVIEW

**Comment by Zero3K** [comment]
https://github.com/bluesky-social/indigo/pull/579

**Comment by kisaragi-hiu** [comment]
Marking as draft for now until I come around to remove the workaround.

**Comment by Zero3K** [comment]
I read in another PR that they are working on their own hashtag implementation. The PR is at https://github.com/bluesky-social/indigo/pull/582.

**Comment by kisaragi-hiu** [comment]
That is the backend special support for searching for hashtags, and would still need this PR or something equivalent to show up in the frontend.

**Pull request merged**
