### PR TITLE
fix timestamp overflow in quotes

### PR DESCRIPTION
**Pull request by haileyok**
## Why

Fixes https://github.com/bluesky-social/social-app/issues/3717

For some reason we were setting `maxWidth` on the text for web and iOS vs using `flexShrink`. We actually use `flex` on Android, so I'm unsure why we were adding additional space here on iOS.

In any case, using `maxWidth` rather than `flex`/`flexShrink` causes problems with `<Text>`. Without `flex`, the text component won't be able to properly break text when it should (or, at least, not well). This was never really a problem because it would break before we reached the end of the container, but now that we have year old posts, its' getting bad.

## Test Plan

So this bit us a tad bit before, so here's a video to display the differences on both iOS and on web with this change. The timestamp does move a bit on iOS, but it actually allows us to see more of the handle so I think that's a win here honestly.

Probably just need to think about if we like this or not. Maybe we want a bit more padding?

https://github.com/bluesky-social/social-app/assets/153161762/e918640d-e2f8-42dc-9f07-83b7c32511a9

### CODE REVIEW

**Comment by estrattonbailey** [comment]
Seems net-positive overall. If it looks good on Android I'm +1

**Comment by haileyok** [comment]
This also fixes this problem

image

**Comment by haileyok** [comment]
So it looks like this now

Screenshot 2024-04-28 at 7 33 42 PM

**Comment by haileyok** [comment]
Pushed one more change here:

- Android behaves the same as it always has
- Web stays at the 80% we had before as well
- iOS expands to 90% since we have room. We don't want to use 100% because it looks a little too close to the side of the screen, but 80% is giving a way a lot of free real estate too

**Pull request closed without merging**
