### PR TITLE
Italian Localization

### PR DESCRIPTION
**Pull request by Titianbeetle**
New strings translated for v.1.75

### CODE REVIEW

**Comment by pfrazee** [comment]
@Titianbeetle can you get a second italian speaker to review this? We always want a confirmation

**Comment by marcomaroni** [comment]
I'm available to collaborate with @Titianbeetle to review the italian translation.

**Comment by Titianbeetle** [comment]
@pfrazee I am in a bit of a pickle here! @marcomaroni came in as a second participant and did a few corrections (see [https://github.com/Titianbeetle/social-app/commit/71bdb7b806b806e8aab3013b097f2a28e9de69c4](url) ,which I have implemented. However, for reason beyond my jurisdiction, his account has been cancelled by GitHub (go figure!) so I am bit stuck as I cannot find any other Italian speaker available on this platform. Also, there is now an error in the check which wasn't there early and I have no idea what caused it. I will put out a call to see if someone else is willing to help and if not I may put an end to my stint as volunteer translator :(

**Comment by surfdude29** [comment]
> Also, there is now an error in the check which wasn't there early and I have no idea what caused it.

I don't think you need to worry about the PR labeler /webpack-analyzer error, I got that too on my PR. I might be wrong on this but I think that is only applicable for Bluesky team members?

**Comment by haileyok** [comment]
Heh yea, the labeler is a bit wonky when working with other people's PRs. I disabled it for external contributors now, so if you merge in main it should stop yelling at you.

**Review by pfrazee — APPROVED** [review]

**Pull request merged**
