### PR TITLE
Options for selecting preferred dark theme

### PR DESCRIPTION
**Pull request by haileyok**
fixes https://github.com/bluesky-social/social-app/issues/2595

Adds preference in settings to choose between the default dark theme or the OLED dark theme. To support this, we needed to make some changes (which incidentally will make adding additional themes down the road much easier):

- Create a `oledTheme` theme which uses all of the base tokens from `darkTheme` but sets `backgroundColor` to `trueBlack`
- Both the ALF and the legacy `ThemeProvider` take in the name of a theme now rather than a particular color mode. Options are `light`, `dark`, or `oled`. Assuming that `dim` is another theme option that is anticipated, it's now as easy as just updating the theme name type to add more.
- `useColorMode` and `useSetColorMode` is changed to `useThemePrefs` and `useSetThemePrefs`. Respectively, both contexts have `colorMode, darkTheme` and `setColorMode, setDarkTheme` as their values
- `useColorModeTheme` is changed to return the memoized theme name, and we handle the logic here to determine which theme name to use regardless of the color mode being system/light/dark.

Additionally on web since there are some styles inside of the root HTML document, it seems better to change this logic a bit. Instead of relying on `@media` here, we can use use the existing `updateDocument()` from the color mode context to set the particular theme that is being used (light, dark, or oled). Instead of adding/changing the class name inside of the context's `useEffect` however, we can handle that when the `useColorModeTheme` memo updates.

(If there is some reason that `@media` was being used over RN's `useColorScheme()` we can add that logic back. I tested that on Gnome and KDE, macOS, and Windows 11 and it seems to work fine)

https://github.com/bluesky-social/social-app/assets/153161762/d3fd59d5-fdeb-46cc-ab3a-8ba3e7b9d1ec

### CODE REVIEW

**Comment by haileyok** [comment]
Inclined to maybe have a separate screen for appearance preferences, but I'll leave as is for now. Assuming that eventually things here will migrate to using ALF anyway.

OLED probably isn't the right name you want for the theme itself either. Probably could give the two different themes better names than just "Default" and "OLED".

**Comment by surfdude29** [comment]
> OLED probably isn't the right name you want for the theme itself either. Probably could give the two different themes better names than just "Default" and "OLED".

Many users may not be familiar with the term OLED so I think you're right. A few options that come to mind are "Dim / Dark / Lights down" for dark but not pure black and "Dark / Night / Lights out" for pure black/OLED.

**Comment by Hima-Zinn** [comment]
I think "Pale Blue"or"Sky Blue"... and "Black"or"True Dark"... are good option names.

"Default" → "Pale Blue"or"Sky Blue"...
"OLED" → "Black"or"True Dark"...

Also, it would be more useful if the "Dark Theme" could be displayed only when "Dark" is selected.

**Comment by haileyok** [comment]
@Hima-Zinn Yea, it only displays if dark mode is selected or if "System" is selected (since you'll still end up in dark mode at night, and you'll want to pick an option for that time period)

**Comment by Hima-Zinn** [comment]
@haileyok Thank you. I appreciate your concern.

**Comment by Juicysteak117** [comment]
Fantastic, thank you Hailey!

**Comment by haileyok** [comment]
moving this to https://github.com/bluesky-social/social-app/pull/2722

**Pull request closed without merging**
