### PR TITLE
Pull upstream bugfixes to bottom-sheet

### PR DESCRIPTION
**Pull request by pfrazee**
Noticed the swipe gestures failing on the bottom-sheet. Pulling latest upstream fixed it.

### CODE REVIEW

**Comment by gaearon** [comment]
How to repro the issue?

**Comment by pfrazee** [comment]
Before updating, I found all bottom sheets were failing to swipe away (down motion) and sheets with multiple snap points such as the account switcher would not swipe upward.

**Review by gaearon — APPROVED** [review]
i trust you but couldn't repro for some reason

**Comment by pfrazee** [comment]
That's worrisome. I wonder how that can happen -- I was able to repro on device and in a simulator. No harm merging but, very odd.

**Pull request merged**
