### PR TITLE
[🐴] Pill for additional unreads when coming from background

### PR DESCRIPTION
**Pull request by haileyok**
Stacked on https://github.com/bluesky-social/social-app/pull/4027

Needs some styling work, but not sure how to make it look right now.

Go to about 2/3 of the way through the video to see effect when foregrounding.

https://github.com/bluesky-social/social-app/assets/153161762/e70500f1-281a-407a-89ac-47214b82c304

### CODE REVIEW

**Comment by mozzius** [comment]
Looks super nice, but I'd expect something to happen when you click on it? Not sure if I'd expect it to scroll to bottom or scroll to the oldest unread message though

**Review by mozzius — APPROVED** [review]
Ok I understand more about how this is supposed to be working. This looks good (great in fact) but we should also consider showing this when any new message comes in and you're not scrolled to the bottom

**Comment by haileyok** [comment]
Nice, as long as we're okay with the look then we can definitely do that!

**Comment by haileyok** [comment]
Also I'm torn on the "should it scroll" too. On one hand it would let you get to the bottom quickly, on the other you'd end up missing the new content 🤔 

Still think I lean more toward making it scroll down

**Pull request merged**
