### PR TITLE
Edit mode on switch account dialog

### PR DESCRIPTION
**Pull request by mozzius**
Required for settings redesign

https://github.com/user-attachments/assets/cd5ddeb3-fac6-4ce0-bddb-5b8df080fc37

### CODE REVIEW

**Comment by mary-ext** [comment]
It seems like it'd be prone to accidental taps, e.g. wanting to remove X account but ended up removing Y.

**Comment by mozzius** [comment]
The tap target is no different than the normal list? Do you think there should be a confirm prompt?

**Comment by mary-ext** [comment]
Yeah, though perhaps adding a confirmation might add too many taps? Considering how annoying it is to sign-in again it seems appropriate.

**Comment by mozzius** [comment]
Closed in favour of https://github.com/bluesky-social/social-app/pull/6131

**Pull request closed without merging**
