### PR TITLE
Fix RSS URLs treated as internal

### PR DESCRIPTION
**Pull request by estrattonbailey**
Emily noticed that RSS URLs are treated as internal atm. This fixes that.

Test post: https://bsky.app/profile/emily.bsky.social/post/3kn52xdg3cc2a

### CODE REVIEW

**Comment by haileyok** [comment]
Work on web but on native it's giving `useOpenLink` the value `/profile/haileyok.com/rss`. We might need a router update for this too (I guess could also just prepend `https://bsky.app` if the url starts with `/` but that doesn't feel good)

**Comment by estrattonbailey** [comment]
@haileyok I think it's OK to prepend the host, since we DO want RSS links to open in a browser. Right?

But we do need some sort of router update to handle Safari trying to link the user back to the app, which results in a 404.

CleanShot 2024-03-08 at 17 37 11@2x

**Comment by haileyok** [comment]
Okay yea, that should be fine. As for the Safari issue, yea the router is probably trying to push to the same relative path I think...maybe the router should just push to the profile page in that case?

**Comment by estrattonbailey** [comment]
Yeah I think just route to profile is fine. Not sure what else we could do since iOS will try to universal link to the app for those URLs 🤔

**Comment by haileyok** [comment]
Okay, this might be a solution. We can modify the router to allow for an array of possible paths rather than a single one.

_That being said_, now need to make sure that the Go server is handling `/rss` for us before we even hit the router. Going to build and see.

**Comment by haileyok** [comment]
Okay yea, this works. The go server handles the RSS on its own:

```go
	// profile RSS feed (DID not handle)
	e.GET("/profile/:ident/rss", server.WebProfileRSS)
```

Screenshot 2024-03-08 at 5 49 14 PM

The router will still catch `/rss` here though on native since the deeplink goes to `bluesky://` instead of the Go server. Might be useful to have multiple routes for another reason in the future anyway.

**Review by haileyok — APPROVED** [review]
As long as we are okay with the router change, the rest of this works on both platforms.

**Pull request merged**
