### PR TITLE
Fix 651 Make followers and following button into a `<Link>`

### LINKED ISSUE #651: "followers" and "following" should be <a> elements
**Is your feature request related to a problem? Please describe.**

<a> have additional functionality such as link preview (bottom left of Chrome) on hover, open in new tab, probably some a11y benefits, etc

**Describe the solution you'd like**

Change or wrap <div> in <a>

**Describe alternatives you've considered**

Chrome "duplicate tab"

**Additional context**

I can implement this if people think it's a good idea. Actually I reported a similar issue prior to open-source, and it seems to have been fixed. So we can probably `git blame` and follow the same pattern.

### PR DESCRIPTION
**Pull request by ansh**
Fixes #651

### CODE REVIEW

**Comment by pfrazee** [comment]
Does this actually turn those buttons into `<a>` tags? I dont think it will unless we specify an href attribute on them

**Comment by ansh** [comment]
@pfrazee Even `asAnchor` and adding `href` doesn't seem to make them into `<a>` tags. I can look more into that but might be how some accessibilityType components get rendered.

Current solution makes the buttons accessible and gives current pointer type which is the main issue.

**Comment by pfrazee** [comment]
Ah yeah that's possible. If we include an `href` that should enable cmd/ctrl+click though yeah? Also maybe we want to drop the button accessibilityType prop if we're able to make it an `<a>`?

**Comment by ansh** [comment]
Makes sense @pfrazee I can do that

**Comment by ansh** [comment]
@pfrazee Done

Also made some improvements are de-duping some code, and making tracking events better

**Review by estrattonbailey — APPROVED** [review]
V nice

**Review by pfrazee — APPROVED** [review]
🚀

**Pull request merged**
