### PR TITLE
Update Japanese translation

### PR DESCRIPTION
**Pull request by tkusano**
- translate new messages for https://github.com/bluesky-social/social-app/commit/cfb8a3160e0092990bafd05cb97006720400448a (priority notifications)
- unified translation of "something went wrong"

### CODE REVIEW

**Comment by tkusano** [comment]
@dolciss @Hima-Zinn @middlingphys @hibiki
New PR is created for Japanese translation.

**Review by Hima-Zinn — COMMENTED** [review]
Thank you for your working!

**Comment by tkusano** [comment]
translate new labels added by LinkLab, and so on

**Review by dolciss — COMMENTED** [review]
ALL RIGHT, thank you for translations!

**Comment by tkusano** [comment]
Follow the changes made by https://github.com/bluesky-social/social-app/commit/8ddb28d3c54b63fb81ca361e741e5a6a46c1d25f

**Comment by tkusano** [comment]
Follow the changes made by https://github.com/bluesky-social/social-app/commit/b0e130a4d85f2056bddcbf210aa7ea4068d41686 , https://github.com/bluesky-social/social-app/commit/c78e9e31472af42a7920af18186f9ae499595100 , and https://github.com/bluesky-social/social-app/commit/7f292abf51a4cd4e25702c33a3ed75f25be5b3a3

**Comment by surfdude29** [comment]
@tkusano Looks like something might have happened with the latest commits?

**Comment by tkusano** [comment]
I changed the environment for translation tasks, so it might have some problem occurred. I'l check later.

**Comment by tkusano** [comment]
revert & re-merged

**Comment by tkusano** [comment]
Follow fff2c079c25548 and 5bf7f3769d005e

**Comment by tkusano** [comment]
- follow code updates
- unify the translation of "toggle" to "切り替え"

**Comment by tkusano** [comment]
Follow https://github.com/bluesky-social/social-app/commit/836754213827ebdb3c4af2a115a70ab4364e1e94 and https://github.com/bluesky-social/social-app/commit/6f450b4982405535ebccba24f2e32940b161d57f

**Comment by tkusano** [comment]
Translate strings added by  https://github.com/bluesky-social/social-app/commit/b6e515c664d51ffe357c3562fd514301805ade8c

**Comment by tkusano** [comment]
- Unify translations of "hidden" and "community" ("隠された" -> "非表示", "コミュニティー" -> "コミュニティ")
- Add new translations related to https://github.com/bluesky-social/social-app/commit/723896a45f0fdf9612e5b6bb2a82ac7e894928ba

**Comment by tkusano** [comment]
Translated "show quotes" related strings https://github.com/bluesky-social/social-app/commit/56ab5e177fa2b24d0e5d9d969aa37532b96128da

**Comment by tkusano** [comment]
Update translations for threadgate related updates.

**Review by pfrazee — APPROVED** [review]
Thanks all!! <3

**Pull request merged**
