### PR TITLE
Fix minor issues in es localization

### PR DESCRIPTION
**Pull request by dgruano**
After seeing a couple of typos I decided to dive a bit deeper in the Spanish translation. Here are the changes I made:

- Use "etiqueta" instead of "tag"
- Use "eliminar" instead of "remover"
- Unify "entrar en pantalla completa"
- Use "Clic" instead of "Click"
- Use "paquete de inicio" instead of "pack de inicio"
- Unify use of "trasladado" instead of "mudado"
- Unify use of "solo" instead of "sólo"
- Unify use of "feed" instead of "noticias"
- Unify use of quotes for "me gusta" as "likes"
- Improve sentences using "2FA"
- Unify sentences mentioning quote posts (citas)
- Other small inconsistencies
- Tú vs usted inconsistencies:
  - agregue -> agrega
  - inténtelo -> inténtalo
  - cierre -> cierra
  - su -> tu
  - complete -> completa
  - comience -> comienza
  - seleccionaba -> seleccionabas
  - intentaba -> intentabas
  - puede -> puedes

However, I also noticed several inconsistencies that should be discussed with other contributors and translators. I have noted some cases of these but have tried to not modify them for now:
  - Post: use of "post" and "publicación"
  - Repost: use of "repost"/"repostear" and "republicación"/"republicar"
  - Add: use of "agregar"/"agrega" and "añadir"/"añade"
  - Feed: use of Feeds in uppercase
  - Video: use of vídeo (es-ES) or video (mentioned in #6691)
  - User and account ("usuario" and "cuenta")
  - Punctuation consistency
  - Uppercase and lowercase consistency

Happy to hear your thoughts!

### CODE REVIEW

**Comment by auroursa** [comment]
There's also an open Spanish translation PR here. #7233 

Would you mind discussing it with them? It would be even better if it could be integrated into the same PR.

**Comment by guilherme-codes** [comment]
Could you please, update ChangeHandleDialog.tsx:250 for this PR?

```
#: src/screens/Settings/components/ChangeHandleDialog.tsx:250
msgid "If you have your own domain, you can use that as your handle. This lets you self-verify your identity. <0>Learn more here.</0>"
msgstr "Si tienes tu propio dominio, puedes usarlo como tu nombre de usuario. Este permite auto-verificar tu identidad – <0>obtén más información</0>."
```

**Comment by GersonLazaro** [comment]
> Could you please, update ChangeHandleDialog.tsx:250 for this PR?
> 
> ```
> #: src/screens/Settings/components/ChangeHandleDialog.tsx:250
> msgid "If you have your own domain, you can use that as your handle. This lets you self-verify your identity. <0>Learn more here.</0>"
> msgstr "Si tienes tu propio dominio, puedes usarlo como tu nombre de usuario. Este permite auto-verificar tu identidad – <0>obtén más información</0>."
> ```
> 
> image

Hi @guilherme-codes. I added this change to the [PR](https://github.com/bluesky-social/social-app/pull/7233). There, we are centralizing these changes along with other corrections to the Spanish localizations.

**Comment by auroursa** [comment]
If @dgruano agrees that #7233 includes all the expected changes from this PR, I think we can go ahead and close this one.

**Pull request closed without merging**
