### PR TITLE
Finnish localization

### PR DESCRIPTION
**Pull request by jaoler**
Finnish (fi) translation for Bluesky. The translation has been done and reviewed by three individuals who speak Finnish as their native language.

### CODE REVIEW

**Comment by msarjakoski** [comment]
Having reviewed the Finnish translations I feel they are very well crafted and that they fit very well as the first public version. I might have some minor suggestions, but I think it would be better to see the translations live in the real context.

**Review by Yangbblood — COMMENTED** [review]
Translation appears ok to me!

**Comment by valoisin** [comment]
Very good translation. Hyvää työtä.

**Comment by jaoler** [comment]
Added new untranslated strings in to Finnish messages.po. I accidentally edited the English file first, then replaced it with the original. Everything in okay now.

**Review by pfrazee — APPROVED** [review]
Wonderful! Thank you!

**Pull request merged**
