### PR TITLE
Fix & Add: Japanese Translation

### PR DESCRIPTION
**Pull request by Hima-Zinn**
@tkusano @dolciss @oboenikui @noritada @middlingphys @hibiki @reindex-ot
Once reindex-ot san updated the Japanese display at https://github.com/bluesky-social/social-app/pull/2961, but since it was not merged easily, I decided to take the initiative to work on it.

My policy is not to delete or add too many files, but to use the files originally in the main branch.

I have taken over from the previous PR, but if there are any mistakes or improvements, please feel free to review.

### CODE REVIEW

**Comment by tkusano** [comment]
@noritada さんの手順ならdiffが見やすいかなと思います
https://bsky.app/profile/noritada.bsky.social/post/3kirmusi7za2c

**Comment by tkusano** [comment]
https://github.com/bluesky-social/social-app/tree/main のPOが更新され、conflictが発生してます。

そして、ハッシュタグをクリックした時にアプリで表示されるメッセージ周りのmsgidが変更になってます。

あと、 https://github.com/bluesky-social/social-app/pull/2961#pullrequestreview-1910409283 でもコメントしましたが、メニューでの表示の見た目を揃えるために文字列頭の「このユーザーによる～」を文字列末の「（このユーザーのみ）」に変えたほうが見やすいかもしれないと思いました。

**Comment by Hima-Zinn** [comment]
OK.
I'm busy right now and will address the additions in the update later.

I will also address the hashtag display part at that time.

**Comment by Hima-Zinn** [comment]
@tkusano @dolciss @oboenikui @noritada @middlingphys @hibiki @reindex-ot
Main branch was being updated frequently and causing conflicts, so it was moved to https://github.com/bluesky-social/social-app/pull/3196.

**Pull request closed without merging**
