### PR TITLE
Update Post for Postar

### PR DESCRIPTION
**Pull request by maisondasilva**
The line I translated refers to this Post, right? If not, you can deny the merge

Furthermore, I noticed that the line was translated but it did not appear in the final translation! This doesn't just happen in the Portuguese translation, it happens in all!

https://github.com/bluesky-social/social-app/blob/56021ccda55e0b30738d4689d3eaa52e8f0c3e96/src/locale/locales/pt-BR/messages.po#L2577
https://github.com/bluesky-social/social-app/blob/56021ccda55e0b30738d4689d3eaa52e8f0c3e96/src/locale/locales/pt-BR/messages.po#L2578

image

### CODE REVIEW

**Comment by maisondasilva** [comment]
@ansh

**Comment by ansh** [comment]
@maisondasilva That line has actually not been localized! It's https://github.com/bluesky-social/social-app/main/src/view/com/composer/Composer.tsx here

**Comment by maisondasilva** [comment]
@ansh Thanks for the update, This line below is correct and is for this word Image Post, right?

image


image

**Comment by ansh** [comment]
@maisondasilva Yes!

**Comment by maisondasilva** [comment]
@ansh Thanks fast replay
Can you merge it for me, thanks

**Comment by maisondasilva** [comment]
@ansh @pfrazee Can you merge this order? I made a new one for the translation on msgid "What's up?"

https://github.com/bluesky-social/social-app/issues/2450

**Comment by ansh** [comment]
So we can pass a `context` prop to Post and that is how we should get this done. I'll be opening a new PR for that!

**Pull request closed without merging**
