### PR TITLE
RNUITextView, selectable post contents for main thread post

### PR DESCRIPTION
**Pull request by haileyok**
Fixes https://github.com/bluesky-social/social-app/issues/954
Fixes https://github.com/bluesky-social/social-app/issues/1102 although it might be worth exploring easier alt-copy options in the future. At a minimum though, this allows for that selection.

https://www.youtube.com/watch?v=0aufAdmfKkE

## RNUITextView Module
React Native's `Text` component allows for "infinite" nesting of further `Text` components. To make a true "drop-in",
we want to do the same thing.

To achieve this, we first need to handle determining if we are dealing with an ancestor or root `UITextView` component.
We can implement similar logic to the `Text` component [see Text.js](https://github.com/facebook/react-native/blob/7f2529de7bc9ab1617eaf571e950d0717c3102a6/packages/react-native/Libraries/Text/Text.js).

We create a context that contains a boolean to tell us if we have already rendered the root `UITextView`. We also store
the root styles so that we can apply those styles if the ancestor `UITextView`s have not overwritten those styles.

All of our children are placed into `RNUITextView`, which is the main native view that will display the iOS `UITextView`.

We next map each child into the view. We have to be careful here to check if the child's `children` prop is a string. If
it is, that means we have encountered what was once an RN `Text` component. RN doesn't let us pass plain text as
children outside of `Text`, so we instead just pass the text into the `text` prop on `RNUITextViewChild`. We continue 
down the tree, until we run out of children.

On the native side, we make use of the shadow view to calculate text container dimensions before the views are mounted.
We cannot simply set the `UITextView` text first, since React will not have properly measured the layout before this
occurs.

As for `Text` props, the following props are implemented:

- All accessibility props
- `allowFontScaling`
- `adjustsFontSizeToFit`
- `ellipsizeMode`
- `numberOfLines`
- `onLayout`
- `onPress`
- `onTextLayout`
- `selectable`

All `ViewStyle` props will apply to the root `UITextView`. Individual children will respect these `TextStyle` styles:

- `color`
- `fontSize`
- `fontStyle`
- `fontWeight`
- `fontVariant`
- `letterSpacing`
- `lineHeight`
- `textDecorationLine`

## Parity on Android

Few small changes:
- Remove the `Link` wrapper on the main post thread item. There is no need for this to be a touchable opacity, and it looks bad when selecting text
- Unsure about this one...I set `PostThread`'s `removeClippedSubviews` to `false`. There's a bug in RN (seemingly an Android ListView related thing) where `selectable` won't work inside of a `FlatList`. Oddly, this prop wasn't set to begin with, and the default is supposed to be `false`. Regardless, I only considered this viable since we probably can rely on `PostThread` to be relatively small (instead of say the feed that will infinitely continue). I don't notice perf issues on the few devices I have, but...

See: https://github.com/facebook/react-native/issues/26264
https://stackoverflow.com/questions/11064115/make-items-within-listview-selectable
https://stackoverflow.com/questions/31726470/how-i-can-create-text-selection-in-listview-item

This is probably fixable though, if it is a perf issue.

### CODE REVIEW

**Comment by pfrazee** [comment]
🚨 s-tier PR alert 🚨

is this ready for review, @haileyok ?

**Comment by haileyok** [comment]
@pfrazee s-tier is the only way to live

ready now, made alt text selectable as well now. there's some changes/improvements that can continually get made to the module, but right now all the needed Text features work.

**Comment by haileyok** [comment]
Oh, this was also tested with voiceover and accessibility inspector. Things are fine there (aside from the just overall screen reader issues that already exist)

**Comment by haileyok** [comment]
cleaned up a bunch of stuff while writing a little post about doing this. otherwise been testing it all day and its working great on my machine™

**Comment by pfrazee** [comment]
fire fire fire

**Comment by haileyok** [comment]
just to make sure, ran a quick profile on this just to see if there were any perf implications (that would be negligible anyway but). looks like like its is on near equal footing with Text (i mean this is <1ms renders here so its really irrelevant, but point is there's nothing goofy 👍 )

Screenshot 2024-01-16 at 3 26 42 PM

Screenshot 2024-01-16 at 3 28 47 PM

also sneaking in a little adjustment to the alt text expansion so it is less jarring.

**Comment by haileyok** [comment]
okay that should do it, fixed a few of the minor things i noticed over the past couple days.

**Comment by haileyok** [comment]
@pfrazee yea thats great. im actually dropping expo-modules since you unfortunately cant use the shadowview there. for perfect parity, we want to override flexbox which requires calculating before mount in the shadowview. would rather test that for a bit anyway.

**Comment by haileyok** [comment]
merged main in, this supersedes https://github.com/bluesky-social/social-app/pull/2563 since we need to move the `onPress` event to `<Text>`. Otherwise, we will get interference with the native selection gestures (press and hold) and the view itself. Otherwise, same thing.

**Review by pfrazee — APPROVED** [review]
Works super well. Tested in simulators and on-device iOS. Now waiting for android test device to juice up and just triple check there.

I'm okay with removing the `<Link>` wrapper on posts in the post thread. Didn't notice any real difference in the behaviors on any platform.

Android's alt-text selection is still wonky, even testing here. What I see now is that it enters selection state but then fails to retain afterwards. I'll try to address this in a separate PR.

I did have to make one change for Web. It was giving me a function-not-found:

```diff
diff --git a/modules/react-native-ui-text-view/src/index.tsx b/modules/react-native-ui-text-view/src/index.tsx
index ada5c4d9..d5bde136 100644
--- a/modules/react-native-ui-text-view/src/index.tsx
+++ b/modules/react-native-ui-text-view/src/index.tsx
@@ -24,6 +24,7 @@ export interface RNUITextViewChildProps extends TextProps {
 }

 export const RNUITextView =
+  UIManager.getViewManagerConfig &&
   UIManager.getViewManagerConfig('RNUITextView') != null
     ? requireNativeComponent<RNUITextViewProps>('RNUITextView')
     : () => {
@@ -31,6 +32,7 @@ export const RNUITextView =
       }

 export const RNUITextViewChild =
+  UIManager.getViewManagerConfig &&
   UIManager.getViewManagerConfig('RNUITextViewChild') != null
     ? requireNativeComponent<RNUITextViewChildProps>('RNUITextViewChild')
     : () => {
```

**Comment by haileyok** [comment]
Unfortunate about the Android issue. I'll play with it on a real device and see what it feels like there.

**Comment by pfrazee** [comment]
Well, weirdly on my test device the alt text selection worked fine. Let's give it a deploy and see how it goes.

**Comment by pfrazee** [comment]
Had to do a local squash & merge in my CLI because of my changes, so GitHub isn't detecting as merged but indeed this is!!

**Pull request closed without merging**
