### PR TITLE
[APP-834] Allow @ing someone in post directly from profile

### LINKED ISSUE #1206: Make it easier to write to somebody when I'm looking at their profile
**Is your feature request related to a problem? Please describe.**

I'm looking at a profile and would like to send that person a message / write to that person, but don't see a button or link to do so. 

**Describe the solution you'd like**

In twitter, when I look at a profile, and from there start a new message, the '@ profile handle' is pre-filled in my new message. 

In instagram, when I look at a profile, I have a 'Message' button. 

Im mastodon, when I look at a profile, I can click on the ... and have "Mention '@ profile handle' " – while that is a strange way to phrase it, it lets me send a message to the person. 

**Describe alternatives you've considered**

Typing @ and the person's handle – but that's so much work ;)   

**Additional context**

Desktop and mobile.

### PR DESCRIPTION
**Pull request by ansh**
Closes #1206 

- [x] web
- [x] ios
- [x] android

Web
https://github.com/bluesky-social/social-app/assets/8207733/e0cab755-d7f1-4e55-9c6c-00d9a3db5786

iOS
https://github.com/bluesky-social/social-app/assets/8207733/a98c42c8-1cc3-45da-8d73-66f0252abbe4

### CODE REVIEW

**Comment by mschwendener** [comment]
Not sure if anybody will see this here.. 

at the moment, starting a post from somebody's profile looks like this for me, Chrome on MacBook

screenshot_4568

**Comment by estrattonbailey** [comment]
@mschwendener great call, Mozzius noticed and fixed for us already in #1552  🎉 will be included in next release!

**Comment by mschwendener** [comment]
Good to know, thank you. 

> users with invalid handles 

user in my example is @neilhimself.neilgaiman.com 

now I see that when I click on his handle from https://bsky.app/profile/manuschwendener.bsky.social/post/3kafnqa6rep2b, I get to https://bsky.app/profile/did:plc:o6ibgputv3kmdq6ebzd27ezx , not https://bsky.app/profile/neilhimself.neilgaiman.com 

If he _does_ have an invalid handle, maybe tell him how to fix it?  ;-)

**Comment by pfrazee** [comment]
we have some inconsistent linking behavior right now yeah

**Comment by mschwendener** [comment]
> starting a post from somebody's profile  
this part is fixed

**Pull request merged**
