### PR TITLE
Updated Polish translation

### PR DESCRIPTION
**Pull request by voi-tech**
Updated the Polish translation to be linguistically correct and consistent with the documentation.

### CODE REVIEW

**Comment by surfdude29** [comment]
Thanks for this! Pinging contributors to #6283 for feedback and review:

@axiand @isulim @matthewgorniak @MStankiewiczOfficial @cyntler

**Comment by axiand** [comment]
Thanks for your contribution. Since GitHub chokes on large pull requests, I'll be addressing my reviews by their line numbers. I hope it's not too much trouble.

As most of this PR appears fine, a lot of these suggestions are revert proposals sorted into a variety of concerns.

- L51, 94, 206, 230, 274, [everywhere else where "repost" and "czat" is used] - I'm not necessarily fully against it, but what's the reasoning for switching to a borrowed word?
- L218, 262, 2795, 2800 - This is one of the things I wanted to tend to eventually. My suggestion is `obserwać wzajemnie`. The current wording is a little ambiguous.
- L234 - Typo?
- L414-440, 1618 - Any reason to abandon brevity?
- L575, 4640, 5686, 6735, 7679 - Typo
- L600, 1796, 2804, 4056, 7552 - Flavor text doesn't need to be 1:1 consistent with the source language. Feels like an unnecessary change.
- L718, 1316, 2219, 4662-4667, 6056, 6714 - New string reads worse in my opinion.
- L1447, 3253, 4581 - It's hard for me to be against this change but it just feels unnecessary.
- L3193, 6279, 7034-7043, 7410, 7414 - I fear that this is going to cause overflow errors. Revert strongly suggested.
- L3822-3848, 4089, 7102, 7477 - This seems incorrect. "lista moderacji" accurately matches the source form whereas "lista moderowana" translates to "moderated list"
- L4505 - "Storybook" is the name of a user interface library.
- L5398-5427, 7029 - "Podaj dalej" conveys the same thing and feels cleaner than this. I also worry about overflow errors due to the increased length. Revert suggested.
- L6967, 7460, 7890 - Incorrect change
- L7110-7119 - Unnecessary.
- L7093 - Possible overflow. Revert or use this suggestion: `Odepnij od str. gł.` or `Odepnij od głównej`
- L7245 - I'm not sure but I think this appears as a series of bubbles under the user profile, could cause overflow with the much longer new string.
- L8035-8039 - Incorrect change from future to present

**Comment by voi-tech** [comment]
@axiand Thanks for such a detailed analysis and all the suggestions! I've already corrected the mistakes you pointed out.

- The word "repost" was initially translated as "opublikować ponownie" but after consulting members of the Polish community, they agreed that "repostować" would be more appropriate. Personally, I would leave it as is or change it to "opublikować ponownie" but that is a longer phrase and might not fit well in certain interface elements.  
- Similarly, with the word "czat" – in my opinion, it aligns better with the app, whereas I translated "conversation" as "rozmowa".  
- "obserwować wzajemnie" doesn't sound very natural in Polish, which was even noted by users who reverted to the English interface because of it. The phrases "również Cię obserwuje" and "również obserwuj" fully capture the meaning of the English original and look good as notifications in the app.  
- `L414-440`, `1618` – without the word "zostało," the phrasing lacks clarity.  
- `L600`, `1796`, `2804`, `4056`, `7552` and `L718`, `1316`, `2219`, `4662-4667`, `6056`, `6714` – my changes are linguistically correct and look better. The previous formulations were often ambiguous and unclear. I fixed the errors found in these sections.  
- `L1447` – I reverted to the previous version.  
- I changed "kod potwierdzający" to "kod weryfikacyjny" because it sounds more natural and clear.  
- I changed "lista moderowana" to "lista moderacji" as per your suggestion. In Polish, "lista moderacji" sounds like the list belongs to people involved in moderation. It also gives the impression that it might be a list showing moderators or moderation-related services. "Lista moderowana" suggests that someone is overseeing the moderation of the list. I'm still not entirely sure what the intended meaning is or what the audience is meant to understand from the name.  
- I changed "rolka aparatu" to "galeria zdjęć".
- I changed "obrazki" to "zdjęcia".

**Comment by axiand** [comment]
Hi, sorry for being slightly late. I meant to review this earlier.

My main thought with regards to borrowed words was that users who are less familiar with English may be a bit stumped by it, but if it doesn't cause any issues down the line then it'll be okay.

Re: mod list translation, I scouted the Polish side of Bluesky after the translation went live, and unlike some particularly *iffy* translations, I didn't see anything being pointed out for mod lists. So I'm assuming it's fine?
Don't take my word as a veto though. I'm open to change if enough people weigh in.

Now I'm going to reiterate on some strings with potential for causing layout bugs. These are high priority, as taking some liberties with linguistics is alright if it means preventing a broken experience:

- `3193` - This string appears in the left sidebar of the app. Changing it to just `Główna` will help maintain consistency with other elements (all of them are single-word) and reduce the chance of layout errors.
- `6279` - Reverting is still on the table imo, but since the English version of the app also has it as two words I won't press too hard.
- `7034` - This one appears in user listings and probably somewhere else that I'm forgetting. I did a quick check using inspect element and indeed, I can see how the layout can get wonky fast if someone has their text size increased or a long username is present. It feels cheap but shortening to `przestań obs.` is the easiest way to fix it.
- Disregard `7414` and `7410`, I think these are accessibility descriptions, not interface elements. Do however pay attention to `5678` and `5686`, because it causes the context menu it's presented in to become incredibly wide. Recommended change `tego użytkownika` -> `autora`

**Comment by axiand** [comment]
Oh, one more thing. `2851` has the wrong case (see the comment a few lines above). Suggested: `Obserwujesz` or `Obserwowane`

**Comment by voi-tech** [comment]
Suggested changes were made.
Changed “użytkownik” to “osoba” where it was logical for consistency. Removed where it was not needed.

**Comment by axiand** [comment]
LGTM 👍 

Thanks again for the many improvements made in this PR

**Comment by axiand** [comment]
@pfrazee 
Pinging for visibility; this is ready for merge.

**Review by pfrazee — APPROVED** [review]
Sweet! Thanks everybody!

**Pull request merged**
