### PR TITLE
Fix wrong translations in zh-CN localization 

### PR DESCRIPTION
**Pull request by mitian233**
In the last pull request #2780 , I made some modification suggestions but they were still pending accepted after merged. 

I thought maybe the contributor didn't see it so I fixed them by myself.

### CODE REVIEW

**Review by auroursa — COMMENTED** [review]
It might have been unintentionally overlooked in [#2780](https://github.com/bluesky-social/social-app/pull/2780). I think these translational modifications are appropriate.

**Comment by auroursa** [comment]
By the way, I noticed you made changes to line 2691, and I think line 2695 also needs to be synchronized for modifications.

**Comment by mitian233** [comment]
Received. 🫡I've made the changes accordingly.

**Comment by auroursa** [comment]
Based on this PR, I'd like to initiate a discussion to minimize developers being distracted by too many PRs.
Do you think we should add "个" -> "2 个邀请码可用" here? There are similar instances in the current translation files.
image

**Comment by mitian233** [comment]
I will correct it later

**Review by auroursa — COMMENTED** [review]
Looks good to me.

**Comment by auroursa** [comment]
Another issue here, it shouldn't be "是的" I personally prefer using "启用".
image

**Review by auroursa — COMMENTED** [review]
Looks good.

**Review by pfrazee — APPROVED** [review]
<3 thanks all!

**Pull request merged**
