### PR TITLE
Fix code2 of several languages in LANGUAGES

### PR DESCRIPTION
**Pull request by tkusano**
`code2` of Luo and Punjabi entries in `LANGUAGES` containes invalid data.

### CODE REVIEW

**Comment by KuwaLee** [comment]
`guj` is also wrong

` {code3: 'gujgu', code2: 'Gujarati', name: 'goudjrati'}`
should be 
` {code3: 'guj', code2: 'gu', name: 'Gujarati'}`

**Comment by tkusano** [comment]
Not only Gujarati, but also Angika were wrong.

**Comment by KuwaLee** [comment]
I regenerate language code and re-order in https://github.com/bluesky-social/social-app/pull/4314

**Comment by tkusano** [comment]
#4314 contains this PR. close this.

**Pull request closed without merging**
