### PR TITLE
Fix embeds for posts

### PR DESCRIPTION
**Pull request by ericvolp12**
The version of `indigo` the `bskyweb` Go service is using is pretty out of date any _might_ be why embeds aren't performing properly.

This change updates the `indigo` version to its current latest and shifts from using `GetPostThread` to the `GetPosts` endpoint to lookup posts when filling an embed.

### CODE REVIEW

**Comment by ericvolp12** [comment]
Oh, that might be what it is? I'm seeing raw `400`s in the logs though. I can set up a routine to refresh the token.

**Comment by pfrazee** [comment]
It looks like https://github.com/bluesky-social/social-app/pull/1256 has some overlap with this; we should make sure all the changes get copied over

**Comment by ericvolp12** [comment]
> It looks like #1256 has some overlap with this; we should make sure all the changes get copied over

Oh, I had half of that stuff in this PR too, I'll move the rest.

**Comment by ericvolp12** [comment]
> I thought the issue w/embeds not working was related to not refreshing the auth token? So embeds might work for ~2 hours and then stop?
> 
> I know I saw @bnewbold's code to switch bskyweb over to using AppView anonymously instead of authing against the PDS.

Oh I just found that PR you were talking aobut, dammit

**Comment by pfrazee** [comment]
@ericvolp12 What's the status here?

**Comment by Jacob2161** [comment]
I believe this was resolved by Bryan's PR to switch bskyweb to using AppView's unauthenticated API

Unless I'm missing something, we should be good.

```bash
$ curl -s "https://bsky.app/profile/nytimes.com/post/3k62ggmmk4k2o" | grep og:
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="Bluesky Social">
  <meta property="og:url" content="https://bsky.app/profile/nytimes.com/post/3k62ggmmk4k2o">
  <meta property="og:title" content="The New York Times (@nytimes.com)">
  <meta property="og:description" content="Simone Biles’s victory at the U.S. Gymnastics Championships on Sunday meant that she broke a 90-year record by becoming the first American gymnast to win eight national all-around titles. Among a crowded and talented field, Biles looked better than ever. nyti.ms/3EjwxuB">
  <meta property="og:image" content="https://av-cdn.bsky.app/img/feed_thumbnail/plain/did:plc:eclio37ymobqex2ncko63h4r/bafkreidihuwhq5fj7l2koyzqyvd2dqo3kzgtmg23pwcvzcfqrkzu3rawfe@jpeg">
```

**Comment by pfrazee** [comment]
Cool 👍

**Comment by ericvolp12** [comment]
Yeah, there were a few more changes in there that reduced the number of requests we needed to make to populate the meta tags and some general house keeping but nothing critical since Bryan's fix.

**Pull request closed without merging**
