### PR TITLE
don't underline handle in post meta

### PR DESCRIPTION
**Pull request by haileyok**
## Why

It looks ugly.

But seriously. Right now, having the single underline for the entire text doesn't look great at all. We can separate them into two components, so they are individually underlined, but the @ doesn't look great.

image

Instead, let's just not underline the handle at all. It is still a link though.

## Test Plan

Hover the display name which should still be underlined, then the handle which should not.

Screenshot 2024-04-16 at 7 10 20 PM

### CODE REVIEW

**Comment by haileyok** [comment]
Ugh, breaks mobile. Hold on.

**Comment by haileyok** [comment]
Okay, mobile before and after:

## Before

Screenshot 2024-04-16 at 7 19 00 PM

## After

Screenshot 2024-04-16 at 7 18 52 PM

**Comment by gaearon** [comment]
There seem to be some unintended layout changes on native.

- Handle jumped a bit closer to top-right than baseline, need to move it back
- Timestamp jumped to the right, needs to stay in place


https://github.com/bluesky-social/social-app/assets/810438/0e74cb0f-8096-43d8-8168-607ef3792396

This PR:

Screenshot 2024-04-17 at 14 24 18

Desired (baseline):

Screenshot 2024-04-17 at 14 24 51

**Review by gaearon — CHANGES_REQUESTED** [review]
needs native fix

**Comment by haileyok** [comment]
Okay, the `flex` needed to be `flexShrink` for smaller handles. But for the life of me I can't see where this padding is coming from

image

image

**Comment by haileyok** [comment]
You have got to be kidding me...it has to be wrapped in `Text`. Otherwise the padding is - seemingly - randomly applied (it's likely how iOS is calculating the text size in reality). Wouldn't even see the shift with some handles but then others would have a full space at the end...

There's still one shift though that I think we should keep. Right now the time since post isn't aligned on the bottom, so we want to either put that there (my preference visually) or center both the handle and the time.

## Before

Screenshot 2024-04-17 at 9 14 54 AM

## After

Screenshot 2024-04-17 at 9 15 18 AM

**Review by gaearon — APPROVED** [review]
i think this works. tested web, ios, android

**Comment by gaearon** [comment]
i changed it back to nbsp (but on the other side) because the padding didn't work on mobile

**Pull request merged**
