### PR TITLE
Correctly load spanish localization

### PR DESCRIPTION
**Pull request by pfrazee**
Looks like we had a bad copy pasta on this one

### CODE REVIEW

**Review by estrattonbailey — APPROVED** [review]

**Comment by maisondasilva** [comment]
I had sent this correction along with the Portuguese language https://github.com/bluesky-social/social-app/pull/2287

https://github.com/bluesky-social/social-app/pull/2287/commits/dc6cd84f90a84d33e94780a5ee6151346b617971

I'm glad this has been fixed!

Maison

**Comment by pfrazee** [comment]
Oh sorry we didn't catch that! Let me check those tests

**Comment by pfrazee** [comment]
Oh nah that's not trying to test all the languages, just a utility function's behavior

**Comment by maisondasilva** [comment]
@pfrazee Thanks for the update, I sent the Portuguese translation, can you escalate it to the right person? I promise to keep the translation updated!

**Comment by pfrazee** [comment]
@maisondasilva I'll let ansh react to that, he's leading translations

**Comment by ansh** [comment]
@maisondasilva I'm taking a look!

**Pull request merged**
