### PR TITLE
Update italian translation

### PR DESCRIPTION
**Pull request by arestifop**
This PR includes the following updates:

Fixed a few incorrect labels.
Added translations for several missing labels.

### CODE REVIEW

**Comment by crazycoder1999** [comment]
Hey @arestifop 
contact me on @dega1999.bsky.social : let's do one unique PR :)

**Comment by mlocati** [comment]
I've added these changes to #6487 (see 0988082389f60f95aeee8958ede79d6988032d16)

**Comment by arestifop** [comment]
Closing this PR since merged in #6487

**Comment by arestifop** [comment]
Closing this PR since merged in #6487

**Pull request closed without merging**
