### PR TITLE
Animate tab indicator

### PR DESCRIPTION
**Pull request by mozzius**
https://github.com/bluesky-social/social-app/assets/10959775/3f0ca62c-6759-4db2-baf0-f7cd3e3773ee

### CODE REVIEW

**Comment by AronBe** [comment]
Hi, I was thinking about adding animation to the indicator. Was there a reason this got closed? Would you like me to revisit this?

**Comment by mozzius** [comment]
Dan has a better PR that actually syncs it with the swipe gesture

https://github.com/bluesky-social/social-app/pull/1696

However, perf is terrible on android. If you can figure out how to make perf not terrible, that'd be great!

**Comment by AronBe** [comment]
Hey, had a busy week at work, but got it working today 💪 will create a PR tomorrow 👍

**Comment by gaearon** [comment]
@AronBe, sorry I didn't see this thread — I've already done the work in https://github.com/bluesky-social/social-app/pull/6868. Happy to look over your implementation though in case there's something I can improve.

**Comment by AronBe** [comment]
Sure, will tag you tomorrow 👍

**Comment by AronBe** [comment]
created my PR at the end :) #6873

I reviewed your approach @gaearon, you found the right one, similar to mine, so end result will be the same, good job! You can take inspiration from mine to add animated indicator to web as well, it is just one extra useEffect.

**Pull request closed without merging**
