### PR TITLE
Fix alignment of posts in Right-To-Left languages

### PR DESCRIPTION
**Pull request by soheilpro**

### CODE REVIEW

**Comment by pfrazee** [comment]
I'm having trouble evaluating this PR -- the before & after look similar on the first platform I tested (Web).

Can you show me screenshots of the effects of this on all 3 platforms?

**Comment by soheilpro** [comment]
When the post is not long enough to fill the whole container width, the dir="auto" attribute has no effect.

Before:
Screenshot 2023-05-17 at 07 51 41

After:
Screenshot 2023-05-17 at 07 51 59

Unfortunately, I can't get the project to build for iOS/Android.

**Comment by snhasani** [comment]
Doesn't work for me either. In some of the components the text element is wrapped by a flex parent with flex-start position.

**Comment by mzarchi** [comment]
LGTM

**Comment by pfrazee** [comment]
This solution doesn't seem to work consistently. We're aware of the problem but I'm going to close the PR since it's not the right fix

**Pull request closed without merging**
