### PR TITLE
:sparkles: Show Offline indicator status across platforms

### PR DESCRIPTION
**Pull request by foysalit**
This PR adds a handy little offline indicator when user goes offline while browsing the app.

https://github.com/bluesky-social/social-app/assets/1919066/12046216-bae6-48a1-9fd1-9dddb0efef13
> Android Demo

### IGNORE - This has changed, checkout screenshots below
https://github.com/bluesky-social/social-app/assets/1919066/12985a0e-d250-4cf3-af3f-7c5782d8ab2a
> Web Demo

Screenshot 2023-08-18 at 11 38 08

> On desktop web

Screenshot 2023-08-18 at 11 38 16

> On mobile web

### CODE REVIEW

**Review by ansh — APPROVED** [review]
This looks great!

**Comment by pfrazee** [comment]
This is nice - let's make sure we test extensively before merging, there's a high chance some layouts assume no element is up there

**Comment by foysalit** [comment]
> This is nice - let's make sure we test extensively before merging, there's a high chance some layouts assume no element is up there

hmm... yeah a lot of the content on mobile and desktop web set the height of the centered content to be 100% which causes the scrollbar to show up when the offline indicator is pushed in at the top.
So, I moved around the indicator's position a bit on web, checkout the new screenshots @pfrazee 
I can't say I love the repositioning since it may be confusing to users to find it in different places on different devices but I hated the scrollbar more.

**Comment by pfrazee** [comment]
I gotta be honest, I'm not sure this is enough of a priority to suss out and merge

**Pull request closed without merging**
