### PR TITLE
Fix Spanish translations for some messages

### PR DESCRIPTION
**Pull request by GersonLazaro**
I corrected some spelling errors in Spanish: 

- "Cuenta ~~elimada~~ **_eliminada_** de acceso rápido". 
- "Arrastra para agregar ~~imagenes~~ _**imágenes**_".
- "Edita tu ~~descripcion~~ **_descripción_** de perfil". 
- "~~Opcion~~ **_Opción_** {0} de {numItems}". 
- "No tienes ninguna ~~conversacion~~ **_conversación_**. ¡Comienza una!".

### CODE REVIEW

**Comment by GersonLazaro** [comment]
Update:  
- The changes from PR #7262 have been merged into this branch.  
- The [requested change](https://github.com/bluesky-social/social-app/pull/7262#issuecomment-2561254026) has been included.  
- I have fixed a couple of additional issues:
  - "Clic aquí para abrir el ~~menu~~ **_menú_** de {tag}"
  - "~~Busquedas~~ **_Búsquedas_** Recientes"

**Comment by dgruano** [comment]
I see there's been a big update (Trending  topics!!) since we opened this PR. I have started to add some translations in my fork. Any thoughts on whether to add them here @auroursa ?

**Comment by auroursa** [comment]
> I see there's been a big update (Trending topics!!) since we opened this PR. I have started to add some translations in my fork. Any thoughts on whether to add them here @auroursa ?

I think that’s a great idea! Let’s update the Spanish translation to the latest version. If you’re willing to do so, please submit a PR to @GersonLazaro’s fork so that we can review them. Looking forward to seeing the updates.

**Review by pfrazee — APPROVED** [review]
Awesome! I'm not going to wait for the trending translations because we're cutting a patch release

**Pull request merged**
