### PR TITLE
Update messages.po

### PR DESCRIPTION
**Pull request by Lucaterzo**

### CODE REVIEW

**Comment by surfdude29** [comment]
Hi, there is already a PR open for updating the Italian localisation: #6188

Would it be possible to suggest those changes over there? 🙏

cc: @marcomaroni-github

**Comment by crazycoder1999** [comment]
Hey Luca
contattami su @dega1999.bsky.social così facciamo un unica PR

**Comment by mlocati** [comment]
I've merged some of these changes into #6487

**Comment by mlocati** [comment]
@Lucaterzo this PR can be closed, isn't it?

**Pull request closed without merging**
