### PR TITLE
Improve notification localization

### PR DESCRIPTION
**Pull request by quiple**
* Makes it easier to localize by providing full context.
```po
#: src/view/com/notifications/FeedItem.tsx:173
#~ msgid "followed you"
#~ msgstr ""

#: src/view/com/notifications/FeedItem.tsx:195
#~ msgid "followed you back"
#~ msgstr ""

#: src/view/com/notifications/FeedItem.tsx:176
#~ msgid "liked your custom feed"
#~ msgstr ""

#: src/view/com/notifications/FeedItem.tsx:168
#~ msgid "liked your post"
#~ msgstr ""

#: src/view/com/notifications/FeedItem.tsx:170
#~ msgid "reposted your post"
#~ msgstr ""

#: src/view/com/notifications/FeedItem.tsx:197
#~ msgid "signed up with your starter pack"
#~ msgstr ""

#: src/view/com/notifications/FeedItem.tsx:261
#~ msgid "{0, plural, one {{formattedCount} other} other {{formattedCount} others}}"
#~ msgstr ""

#: src/view/com/notifications/FeedItem.tsx:288
msgid "{a11yAuthor} and {0, plural, one {{formattedCount} other} other {{formattedCount} others}} followed you"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:262
msgid "{a11yAuthor} and {0, plural, one {{formattedCount} other} other {{formattedCount} others}} followed you back"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:316
msgid "{a11yAuthor} and {0, plural, one {{formattedCount} other} other {{formattedCount} others}} liked your custom feed"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:205
msgid "{a11yAuthor} and {0, plural, one {{formattedCount} other} other {{formattedCount} others}} liked your post"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:231
msgid "{a11yAuthor} and {0, plural, one {{formattedCount} other} other {{formattedCount} others}} reposted your post"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:342
msgid "{a11yAuthor} and {0, plural, one {{formattedCount} other} other {{formattedCount} others}} signed up with your starter pack"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:293
msgid "{a11yAuthor} followed you"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:267
msgid "{a11yAuthor} followed you back"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:321
msgid "{a11yAuthor} liked your custom feed"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:210
msgid "{a11yAuthor} liked your post"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:236
msgid "{a11yAuthor} reposted your post"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:347
msgid "{a11yAuthor} signed up with your starter pack"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:296
msgid "{author} and <0>{0, plural, one {{formattedCount} other} other {{formattedCount} others}}</0> followed you"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:270
msgid "{author} and <0>{0, plural, one {{formattedCount} other} other {{formattedCount} others}}</0> followed you back"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:324
msgid "{author} and <0>{0, plural, one {{formattedCount} other} other {{formattedCount} others}}</0> liked your custom feed"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:213
msgid "{author} and <0>{0, plural, one {{formattedCount} other} other {{formattedCount} others}}</0> liked your post"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:239
msgid "{author} and <0>{0, plural, one {{formattedCount} other} other {{formattedCount} others}}</0> reposted your post"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:350
msgid "{author} and <0>{0, plural, one {{formattedCount} other} other {{formattedCount} others}}</0> signed up with your starter pack"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:308
msgid "{author} followed you"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:282
msgid "{author} followed you back"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:336
msgid "{author} liked your custom feed"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:225
msgid "{author} liked your post"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:251
msgid "{author} reposted your post"
msgstr ""

#: src/view/com/notifications/FeedItem.tsx:362
msgid "{author} signed up with your starter pack"
msgstr ""
```

Tested on the web.

### CODE REVIEW

**Comment by quiple** [comment]
@pfrazee Hello, could you please review this PR?

**Comment by haileyok** [comment]
Pretty nasty merge conflict here, from fixing RTL support. I can look later and clean it up unless you really feel a desire to do it 😅

**Comment by quiple** [comment]
@haileyok I think it's probably done. Thanks for notice!

**Comment by quiple** [comment]
@haileyok Can you please review this PR and also #3912?

**Comment by quiple** [comment]
@estrattonbailey Hello, I was wondering if you could review this PR?

**Review by estrattonbailey — APPROVED** [review]
Wow, thanks for all your work on this, we really appreciate it! Gonna merge into a base branch and test from there 👍

**Pull request merged**
