### PR TITLE
minor search screen ux improvements

### PR DESCRIPTION
**Pull request by haileyok**
Hopefully I am not PR spamming here...apologies if so. This is just some very minor changes but with very noticeable UX improvements:

- Add a hitslop to the cancel and clear buttons on the search screen (and the clear button on the feeds screen search). These are currently rather difficult to press
- Add `keyboardShouldPersistTaps` to`SearchScreenSuggestedFollows`, `SearchScreenMobile` (autocomplete results), and `Feeds`.  Currently you have to dismiss the keyboard before any interaction with the screen can be made.
- Dismiss the keyboard on scroll on `SearchScreenSuggestedFollows`, `SearchScreenMobile`, and `Feeds`. This resolves issues where some content is hidden below the keyboard.

On the last issue, this is certainly a good fix (both in terms of ease and feel). The alternative would be to adjust the content insets when the keyboard is visible. Unfortunately I can't seem to get that to work on `SearchScreenMobile` after the `ScrollView` re-renders. `automaticallyAdjustKeyboardInsets` is known to be a bit buggy, and there are some way better alternatives available if that's something you want to explore: See https://twitter.com/hirbod_dev/status/1668528361457451009 (sorry for bird link)

UX wise, I think that dismissing the keyboard on scroll is the most common behavior, so I don't think there's a big need in this particular case. (I also think this is default behavior on Android even without the prop, but I'm not a big Android user so don't quote me on that)

RocketSim_Recording_iPhone_15_Pro_2023-12-21_01 11 54

RocketSim_Recording_iPhone_15_Pro_2023-12-21_01 12 40

### CODE REVIEW

**Review by pfrazee — APPROVED** [review]
literally had this on my todo list, another awesome contrib. thank you!

**Review by estrattonbailey — APPROVED** [review]
Yesssss

**Comment by pfrazee** [comment]
I still need to test this before we merge but I'll try to today

**Review by pfrazee — APPROVED** [review]
Yeah great stuff as expected, thanks so much hailey

**Pull request merged**
