### PR TITLE
Add partial translations for zh_TW (Traditional Chinese in Taiwan)

### PR DESCRIPTION
**Pull request by kisaragi-hiu**
This PR adds translations for `zh_TW`. `zh_TW` is a distinct dialect from `zh_CN` and thus requires a different translation.

Right now this is 87% translated (881/1004).

### CODE REVIEW

**Comment by auroursa** [comment]
Hello, I'm the maintainer for Simplified Chinese localization. I have completed the translation work for the Taiwan language files. If you don't mind, could you please review my pull request and consider merging your translations into my messages.po file? I would greatly appreciate your assistance. Thank you. [#2781](https://github.com/bluesky-social/social-app/pull/2781)

**Comment by kisaragi-hiu** [comment]
I avoid converting from `zh_CN` (manually or automatically) as that usually results in too many `zh_CN` usages slipping in.

- The internet is 網路 or 網際網路, not 互聯網
- 訊息流 is a very rare translation for "feed". My PR uses "時間軸" which is still imperfect
- Post is never shortened to 帖. It is always 貼文
- "Add <thing>" is generally translated as 新增<thing>, not 添加 (unless it is adding a thing into something, but even then 加入 is used more often)
- 記錄 is always a verb; as a noun it's written as 紀錄 (Not even YouTube Taiwan follows this 100% of the time though)
- Data is 資料 in general, and only 數據 when it is analytics data
- Device is almost always 裝置, not 設備. 設備 is "equipment".
- "Open <thing>" is generally 開啟<thing>, not 打開.

A few other choices I made in my version:

- I always use 您 in accordance to l10n-tw convention (Free Software translation convention in Taiwan), though this isn't a convention followed by, say, Twitter or YouTube.

However, I certainly did miss your PR as I kind of tried to rush something out. I also missed the changes in code that's necessary for the translation to actually apply.

I'll try to merge your version with mine and see how it turns out.

**Comment by auroursa** [comment]
Thank you for your assistance. There are still many areas in my translation that need improvement. I appreciate your help.
I agree that the translation for 訊息流 might not be appropriate, and I would like to leave room for further discussion on that. I have already made modifications to other parts.

**Comment by kisaragi-hiu** [comment]
Closing in favor of #2781.

**Pull request closed without merging**
