### PR TITLE
Improve spanish translation of repost

### PR DESCRIPTION
**Pull request by gonzaloriestra**
Use "republicar" instead of "volver a publicar"

### CODE REVIEW

**Comment by surfdude29** [comment]
There's a PR open for updating the Spanish localization: #6094

Could I suggest you discuss changes on that PR?

cc: @elenatorro

**Comment by gonzaloriestra** [comment]
Sure! Elena is a good friend 😄

**Comment by gonzaloriestra** [comment]
@surfdude29 the other PR has been merged, so I'm reopening this one.

**Comment by gonzaloriestra** [comment]
@hogaza in case you want to help, as you said [here](https://github.com/bluesky-social/social-app/pull/6094#issuecomment-2494180435).

**Review by pfrazee — APPROVED** [review]
No merge conflicts so I'm approving

TYSM!!

**Pull request merged**
