### PR TITLE
Patch to work around a crash in RN internals

### PR DESCRIPTION
**Pull request by gaearon**
Work around https://github.com/facebook/react-native/issues/44842.

I don't have a way to verify whether this works. It would at least be nice to trigger this codepath somehow and verify it runs like before in the common case. That said, the change itself is a trivial change and maybe we can just get it in and try it.

### CODE REVIEW

**Review by haileyok — APPROVED** [review]
Cool, lets try it as long as CI runs

**Comment by cortinico** [comment]
QQ @gaearon: are you folks building React Native Android from source? (see https://reactnative.dev/contributing/how-to-build-from-source).

If not, this change will be ignored as the touched `.java` file is precompiled so the changes to it inside the NPM package will be ignored.

**Comment by gaearon** [comment]
Hmm! We're just using Expo. But I thought in the past that these overrides worked... (cc @haileyok to confirm)

**Comment by gaearon** [comment]
Is just the Android code precompiled?

**Comment by haileyok** [comment]
hmm. we've definitely been able to patch for iOS (we have two load bearing patches for ios right now), don't know if we have patched for android before though! would be fairly easy to test if we want by throwing somewhere and seeing if things break.

**Comment by cortinico** [comment]
> Is just the Android code precompiled?

Yes the Android code is precompiled, the iOS one is not. So unless you turn on build from source on Android, the patches are ignored.

**Comment by gaearon** [comment]
Fascinating — thanks for the heads-up.

**Pull request merged**
