### PR TITLE
Update Ukrainian translation

### PR DESCRIPTION
**Pull request by Dovgonosyk**
Crowdin project for translation and discussion: https://crowdin.com/project/bsky-app-ua

### CODE REVIEW

**Comment by pfrazee** [comment]
@Dovgonosyk Thank you! We need a confirmation review by another Ukrainian speaker. Do you have anybody you could tag in to look?

**Comment by surfdude29** [comment]
@pfrazee Sorry for jumping in here, I just wanted to mention that the Ukrainian translation team do their work on Crowdin (see link above) before opening a PR here on GitHub, so I'm pretty sure that means that they have already agreed on the translations among the native Ukrainian speakers there :)

**Comment by imax9000** [comment]
> @Dovgonosyk Thank you! We need a confirmation review by another Ukrainian speaker. Do you have anybody you could tag in to look?

LGTM

**Comment by romanoid** [comment]
All translations are reasonable.
@imax9000 left some nits for few translations that are a bit clunky and can be improved, but these can be updated in the next sync.

**Comment by pfrazee** [comment]
> @pfrazee Sorry for jumping in here, I just wanted to mention that the Ukrainian translation team do their work on Crowdin (see link above) before opening a PR here on GitHub, so I'm pretty sure that means that they have already agreed on the translations among the native Ukrainian speakers there :)

Oh good to know! Well thanks for the signoffs everybody! Yall rock!

**Review by pfrazee — APPROVED** [review]

**Pull request merged**
