### PR TITLE
show date after 7 days closes #754

### LINKED ISSUE #754: Display the post publication date after 7 days
In [the program source](https://github.com/bluesky-social/social-app/blob/15c1b6ee157471807a723161066ba4ce5e12c0b5/src/lib/strings/time.ts#L25), if the post made by the user exceeds the interval of one month, the program only displays the number of months that have passed, but in my opinion, displaying the date after 7 days like 19/05/2023 from the publication of the post is more acceptable, because the number of days or months is not important. The publication date is important

### PR DESCRIPTION
**Pull request by benharri**
adjust the behavior of ago() to show the date after a week

### CODE REVIEW

**Comment by bnb** [comment]
+1 to the idea

**Comment by ansh** [comment]
Week sounds good but this removes year and month from the function. Was that intentional?

**Comment by benharri** [comment]
they were no longer used. i can put them back in if they're intended to be used in the future

**Review by pfrazee — CHANGES_REQUESTED** [review]
I'm cool with this change, but can we modify this so that it doesn't give the time? It's a bit lengthy as-is.

CleanShot 2023-05-30 at 14 50 31@2x

**Comment by benharri** [comment]
sure thing, will update

**Comment by benharri** [comment]
updated and rebased

**Comment by pfrazee** [comment]
Eugh I feel like such a jerk to ask this but is it possible to get the "May 22, 2023" form instead of the "5/22/2023" form?

**Comment by benharri** [comment]
lol sure thing!

**Comment by benharri** [comment]
should be good to go

**Comment by pfrazee** [comment]
Thank you @benharri for being so patient with me

For some reason this totally screws up the overflow behaviors on iOS

CleanShot 2023-05-30 at 18 29 18@2x

We have some challenges with this on android already, and might need to bundle this with some more robust approach to text layout in the PostMeta control. We either need to wrap our heads around react native's layout styles better (and we've been _trying_) or we need to get some manual sizing controls in there.

**Comment by pfrazee** [comment]
If anybody does get inclined to solve this, bear in mind that post metas are not always the same width

CleanShot 2023-05-30 at 18 31 56@2x

**Comment by benharri** [comment]
Oh yes I've definitely noticed some janky post metas on android (I don't have any ios devices)

Maybe a solution is moving `@author` and the timestamp onto the next line at a certain width?

**Pull request merged**
