### PR TITLE
Add Vietnamese localization

### PR DESCRIPTION
**Pull request by ManhNguyen98**
This PR adds Vietnamese localization. I have translated a few messages and hope this is helpful.

### CODE REVIEW

**Comment by pfrazee** [comment]
Can we get some confirmations from Vietnamese speakers on this?

**Comment by HUNG-rushb** [comment]
> Can we get some confirmations from Vietnamese speakers on this?

The translation is not complete

**Comment by ManhNguyen98** [comment]
Thank you, I think my translation is out of date. And I will update in my next  commit

**Comment by vnphanquang** [comment]
Hi team good work here, the PR is quite far behind with a conflict and there has been lots of fields added in the translation file, so I continue the work at https://github.com/bluesky-social/social-app/pull/6564. Hope you all can hope over there and give it a look. Thanks

**Comment by ManhNguyen98** [comment]
> Hi team good work here, the PR is quite far behind, with conflict with main and there have been lots of fields added in the translation file, so I continue the work at #6564. Hope you all can hop over there and give it a look. Thanks

Hi @vnphanquang ,

Thank you for the update and for picking this up at [#6564](https://github.com/bluesky-social/social-app/pull/6564) We'll take a look at your PR and continue contributing there. Let us know if there’s anything specific you’d like us to focus on.

Thanks again for keeping the ball rolling!

**Comment by vnphanquang** [comment]
#6564 has been merged FYI. Thank you everyone again. The localization is a forever evolving so please feel free to keep contributing. And likewise if you find any error please feel free to reach out to me at vnphanquang.com on bsky.app and  @vnphanquang on all social media.

Thanks!

**Comment by surfdude29** [comment]
This PR can perhaps be closed now that the Vietnamese localization has been merged?

**Pull request closed without merging**
