### PR TITLE
feat(embed): Add support for dark mode

### LINKED ISSUE #5119: [Embeds] Dark/night theme
I'm testing Bluesky embeds, and unless I'm missing something, there doesn't seem to be any support for a 'dark' or 'night' theme:

image

This results in embeds looking quite garish when on pages with dark themes.

**Describe the solution you'd like**

Ideally I would like for embeds to respect the light/dark theme setting of the page/browser/system, like Twitter/X embeds do:

image

image

Bluesky's clients already have a good 'dim' theme that color values can be borrowed from for this.

### LINKED ISSUE #5966: Change background color of embedded posts
### Describe the Feature

It would be nice if we could customize the background color of embedded posts.  I do a lot of embedding, and having just moved to BlueSky from Twitter, it's noticeable.  My blog where I embed them is dark, and the background for embedded BlueSky posts is white, so it sticks out.

### Attachments

_No response_

### Describe Alternatives

_No response_

### Additional Context

[Here's an example](https://joesiegler.blog/2024/10/q-who/) of what I'm talking about - it would be nice if I could make that a darker color.

### PR DESCRIPTION
**Pull request by kakkokari-gtyih**
## What

- Added support for dark mode by using tailwindcss `dark:` modifier.
  - Dark mode is also supported on the landing page.

## Why
Fix #5119 
Fix #5966 
Close #6842 *(I should have said in either of the 2 issues above that I'm working on the patch, sorry for duplication)*

## Additional Info

↓ This image is outdated ("Want more customize?" section is not present in the latest code)

localhost_5173_ (16)

### CODE REVIEW

**Comment by gaearon** [comment]
Hi! Are there any design differences with #6842? I'm not completely opposed to explicit customization but I'd suggest separating that out — I'm not sure we want that. I'd like to better understand the design tweaks first though.

**Review by mozzius — APPROVED** [review]
This is great, thank you!

**Comment by JSDopefish** [comment]
I wondered about that myself.

**Comment by QuinnyPig** [comment]
Yeah I'm not seeing it on embed.bsky.app either--two months after this was merged in...

**Comment by mozzius** [comment]
Yes sorry - we opted not to roll it out until that one gets merged, since otherwise existing embeds will change appearance which is undesirable

**Pull request merged**
