### PR TITLE
Added instructions for .well-known method (supersedes #887)

### PR DESCRIPTION
**Pull request by pfrazee**
Supersedes #887 

CleanShot 2023-07-05 at 19 01 43@2x

CleanShot 2023-07-05 at 19 01 50@2x

### CODE REVIEW

**Review by ansh — APPROVED** [review]
👍🏽

**Comment by rmdes** [comment]
Is there a chance the "no domain panel" option documentation could be augmented to accommodate multi user/multi did under the same domain using the well-known approach?

How would the atproto-did file be constructed to accommodate for like :

domain.com
user1.domain.com
user2.domain.com

Each living with their own DID?

Would it be possible?

**Comment by shaunrobinson** [comment]
> to accommodate multi user/multi did under the same domain using the well-known approach?

I'd also like to know this!

**Comment by LuisPicoES** [comment]
> Is there a chance the "no domain panel" option documentation could be augmented to accommodate multi user/multi did under the same domain using the well-known approach?
> 
> How would the atproto-did file be constructed to accommodate for like :
> 
> domain.com user1.domain.com user2.domain.com
> 
> **Each living with their own DID?**    **<---THIS**
> 
> Would it be possible?

Has anyone tried this approach?

**Pull request merged**
