### PR TITLE
Fix #1328 fix emoji picker scroll on firefox and chrome

### LINKED ISSUE #1283: Emoji Picker does not scroll on Firefox
**Describe the bug**
Emoji picker does not scroll on Firefox

**To Reproduce**

1. Open Firefox
2. Click "New Post"
3. Try scrolling
4. Doesn't work

**Expected behavior**

Scrolling on emoji popup works

**Details**

 - Platform: Desktop Firefox, any version
 - Platform version: Any Firefox version
 - App version: Build version: 1.47.0; Platform: web

### LINKED ISSUE #1328: Web: Have search textbox pull focus in emoji picker after opening
Currently, when opening the emoji picker on web, the cursor stays within the post composer. It would be good to pull focus into the emoji search box when the emoji picker opens given that desired behavior after opening is to immediately search for the desired emoji in most situations.

### PR DESCRIPTION
**Pull request by ansh**
Fixes #1328 and Fixes #1283 

Also:
- [x] open upwards if screen is small

### CODE REVIEW

**Review by estrattonbailey — COMMENTED** [review]
Scroll works, but now I can't dismiss by clicking outside the dropdown. Gotta choose an emoji or press escape :P

**Comment by ansh** [comment]
@estrattonbailey Fixed!

**Comment by pfrazee** [comment]
This does let you scroll, but it scrolls past the mask making things look off.

CleanShot 2023-08-29 at 17 35 07@2x

**Comment by ansh** [comment]
@pfrazee made it responsive with `react-responsive` like the onboarding

**Review by pfrazee — APPROVED** [review]
Perfect :fire:

**Pull request merged**
