### PR TITLE
Profile card hover preview

### PR DESCRIPTION
**Pull request by mary-ext**
Fixes https://github.com/bluesky-social/social-app/issues/2861

Adds profile card preview hovering, this is a very rough implementation meant to get the ball rolling, please take it over :)

There's no delay between hovering-in and hovering-out at the moment, it seems super finicky because if I add a debounce to `hovering`, the preview gets stuck mounted if you head to another page (by clicking the link), it only goes away once you move the cursor

It could be compounded by the use of our custom portal component, and/or Reanimated, but I'm not sure how much time I should be spending on it

I've decided to use `@floating-ui/react-dom` for this because it's a little easier to do floats, if this pull request makes it in, I'll make a subsequent pull request to refactor the web composer to make use of it as well and remove `tippy.js` from the dependency (we don't need multiple popper implementations)

image

### CODE REVIEW

**Comment by mary-ext** [comment]
here's what I tried debouncing the hovering value with

```ts
import React from 'react'

export function useDebouncedValue<T>(value: T, delay: number): T {
  const [state, setState] = React.useState(value)
  const ref = React.useRef(value)

  React.useEffect(() => {
    if (ref.current !== value) {
      const timeout = setTimeout(() => setState(value), delay)
      return () => clearTimeout(timeout)
    }
  }, [value, delay, ref, setState])

  return state
}
```

**Comment by gaearon** [comment]
Refs don’t update values on their own (the value you pass to useRef is only used during first render). Try writing to it from the effect?

**Comment by mary-ext** [comment]
Ah right, I *think* I've set both the ref value and the state in the timeout, and unknowingly removed it while pasting it here

I'll correct that, it doesn't solve the issue with the preview not getting unmounted during page navigation though

**Comment by gaearon** [comment]
No prob, I'll have a look. Thanks!

**Pull request closed without merging**
