### PR TITLE
hide the .bsky from profile, feed and posted mesages

### PR DESCRIPTION
**Pull request by Caitano09**
The username will be clearer and friendlier without breaking the link

https://github.com/user-attachments/assets/c298dc97-9cb0-4df1-8696-b856ddbabe60

### CODE REVIEW

**Review by Vincentroland — COMMENTED** [review]
Explict

**Comment by joncar** [comment]
This would cause significant impersonation problems. Consider a handle that was `official.gov.bsky.mydomain.tld`, it'd show up as `official.gov`!

**Comment by wish13yt** [comment]
The .bsky.social part is intentional... to prevent impersonation..

**Comment by knotbin** [comment]
Even disregarding the impersonation issues brought up, it's not a good idea to just hide .bsky.social. If this idea were to be considered, it should hide the (default) extension of whatever server the user is on, not just .bsky.social.

**Comment by lsuperti** [comment]
In addition to the issues already pointed out by others, if this is ever implemented, it should, by all means, be configurable with a setting, probably disabled by default. There must also be an easy way to see what the actual handle is, regardless of the setting.

**Comment by seboslaw** [comment]
In Skeets (@skeetsapp.com) I have made this optional (configurable in Settings) and it only works with .bsky.social handles. All non-bsky handles are always displayed in full length.

**Comment by knotbin** [comment]
I don't think this is a good idea for the main app. It's already moderately difficult to understand the structure of handles for new users, and this would only make it more complicated and make it easier to fall for impersonation, even if it is an optional setting.

**Comment by Caitano09** [comment]
I understand better now. Thanks guys.

**Comment by mary-ext** [comment]
bsky.social is not the only PDS that exists, just because it is the premiere default PDS does not mean it's allowed to get special treatment

**Comment by knotbin** [comment]
@mary-ext I mentioned this in a previous comment.

> Even disregarding the impersonation issues brought up, it's not a good idea to just hide .bsky.social. If this idea were to be considered, it should hide the (default) extension of whatever server the user is on, not just .bsky.social.

**Comment by ShreyanJain9** [comment]
> @mary-ext I mentioned this in a previous comment.
> 
> > Even disregarding the impersonation issues brought up, it's not a good idea to just hide .bsky.social. If this idea were to be considered, it should hide the (default) extension of whatever server the user is on, not just .bsky.social.

Even that doesn't seem like a great idea to me, handles are intentionally independent from the server you're on.

**Comment by knotbin** [comment]
Each server has a default handle extension though

**Pull request closed without merging**
