### PR TITLE
Adds `.nvmrc` file to `bskyweb`

### PR DESCRIPTION
**Pull request by EvandroLG**
This tiny PR introduces a `.nvmrc` file to the `bskyweb` project.

### CODE REVIEW

**Comment by mary-ext** [comment]
shouldn't it be in toplevel instead?

**Comment by haileyok** [comment]
Yea I think mary's right. Expo 50 requires node 18 now, so there's no harm in putting it there.

**Comment by EvandroLG** [comment]
Done! :)

**Comment by EvandroLG** [comment]
@mary-ext @haileyok?

**Comment by haileyok** [comment]
@EvandroLG Thank you! It got merged in through a PR that built on yours, appreciate it!

**Pull request closed without merging**
