### PR TITLE
[APP-703] Android horizontal scroll registers as tap 

### PR DESCRIPTION
**Pull request by ansh**
After a lot of investigation, it seems as though this issue is caused due to using `Touchables` from core react-native instead of RNGH

https://github.com/dohooo/react-native-reanimated-carousel/issues/150#issuecomment-1086410992

I have replaced them with the ones from RNGH in the `<Link>` component. However, this component is used in a lot of places so extensive testing is required as the `Touchables` from RNGH are not a drop-in replacement.

There are a couple more optimizations that can be done along the same vein (although, they don't have to be part of this PR):
- [ ] improve image tapping behavior (tapping errors here are caused by using `onPressIn`)
- [ ] improve speed to open `PostThread` screen on Android. This is very slow, and that is why sometimes the taps register _after_ the horizontal scroll, which is a bad experience for Android users

### CODE REVIEW

**Comment by ansh** [comment]
@pfrazee I think this PR can be merged after testing. I can add the two other features in later PRs as they require a lot more work and performance monitoring/debugging.

**Comment by pfrazee** [comment]
Holy moly I had to try ten times to get my iphone to run the build and I'm glad I did

This breaks the post controls on iOS

**Comment by ansh** [comment]
RNGH workaround did not work
New workaround:
  // workaround for Android not working well with left/right swipe gestures and TouchableWithoutFeedback
      // https://github.com/callstack/react-native-pager-view/issues/424

**Review by pfrazee — APPROVED** [review]
Okay great this works. We may still need to apply this a couple places (post controls for instance) but let's shipit

**Pull request merged**
