### PR TITLE
Upgrade React Compiler (take two)

### PR DESCRIPTION
**Pull request by gaearon**
Reapplying https://github.com/bluesky-social/social-app/pull/5898 but with a more recent version which should have the fix for https://github.com/facebook/react/issues/31402.

## Test Plan

TBD. I'll walk around the app and verify we don't have the same regression.

### CODE REVIEW

**Comment by gaearon** [comment]
Confirmed the avatar problem we uncovered previously no longer reproduces.

**Review by mozzius — APPROVED** [review]
not tested extensively but seems ok

**Comment by gaearon** [comment]
@poteto `npx react-devtools` (6.0.1-[c7c68ef842](https://github.com/facebook/react/commit/c7c68ef842)) does not show the memo badges for the React Native bundle. Is that expected? I do see the `Symbol.for("react.memo_cache_sentinel")` things in the actual bundle.

**Comment by Malickmimd** [comment]
great work, admire you all specially @gaearon hope one day i'll be in your level to contribute

**Pull request merged**
