### PR TITLE
MobX removal take 2

### PR DESCRIPTION
**Pull request by mary-ext**
Subset of https://github.com/bluesky-social/social-app/pull/3925 (don't close/delete this branch yet)

Refactors the image functionality on the editor and removes remaining the MobX dependency completely. Worth noting that web-only image editor has been ripped out completely (too tangled in mutations which makes it infeasible to do in the same PR, we'll re-add this in a follow-up)

Image states are now immutable. Images are moved into a temporary path dedicated for the composer and they're purged upon closing the composer (IIRC asked @haileyok for where to place the `purgeTemporaryFiles` call).

### Web

- [x] Send an image without alt text
- [x] Enable alt text enforcement, composer should warn on missing alt text, send image with alt text
- [x] Send an external link embed containing a thumbnail (e.g. https://github.com/bluesky-social/social-app)
- [x] Send a GIF embed
- [x] Send a milly post, ensure alt text is present when sharing

### Native (Android)

Untested, haven't dealt with Android Studio in a bit, have gotten around to wrangling with it. There hasn't been any differences between #3925 and this with regards to how the temporary files are dealt with, but extra verification wouldn't hurt
Image editing flow needs testing as well.

### Native (iOS)

Untested, no iOS device.
Image editing flow needs testing as well.

## Follow-ups

https://github.com/bluesky-social/social-app/pull/3942 is required for pulling in the new cropper from https://github.com/bluesky-social/social-app/pull/3925, as we're going to be importing a CSS file from the new package we'd be using for cropping functionality.

### CODE REVIEW

**Comment by mary-ext** [comment]
Need rebasing

**Comment by mary-ext** [comment]
I've rebased this PR and #3942

**Comment by gaearon** [comment]
Can you please rebase and also clarify the relationship between https://github.com/bluesky-social/social-app/pull/3925 and this PR? Is this PR a subset of the changes there"?

**Comment by mary-ext** [comment]
will rebase again tomorrow since it's getting late, PR is a subset of Paul's but only the bits related to removing MobX.

**Comment by mary-ext** [comment]
@gaearon should be ok to review now :ok_hand:

**Review by gaearon — APPROVED** [review]

**Comment by haileyok** [comment]
Just fyi @gaearon I think we need to rm mobx from `package.json` now too haha.

**Comment by gaearon** [comment]
Gave this some testing across platforms, seems solid. Thank you for untangling this and bringing it up to date!

**Pull request merged**
