### PR TITLE
Created Turkish language

### PR DESCRIPTION
**Pull request by atiksoftware**

### CODE REVIEW

**Review by ahmetsagirli — COMMENTED** [review]
Checked.

**Comment by haileyok** [comment]
@atiksoftware @ahmetsagirli Hi! We usually like to have multiple people look over these. Do you have anyone else who might be willing to look it over and give the sign off?

**Comment by atiksoftware** [comment]
@haileyok Hi. Translations were checked by multiple people before being push

**Comment by amiralrouter** [comment]
checked

**Comment by pfrazee** [comment]
Thank you everyone! Merged!

**Pull request merged**
