### PR TITLE
Native toast rework

### PR DESCRIPTION
**Pull request by mozzius**
- New look
- Entry/exit animations
- Icons

Screenshot 2024-07-20 at 17 56 53
Screenshot 2024-07-20 at 17 58 03
Screenshot 2024-07-20 at 17 54 20
Screenshot 2024-07-20 at 17 55 47

### CODE REVIEW

**Review by estrattonbailey — APPROVED** [review]
Nice! I'm +1, and we can continue to improve over time.

Exit animation on iOS isn't working for me though, if that's a quick fix we might as well do that here.

**Comment by haileyok** [comment]
Don't know what the most elegant way to do this would be - first time I looked at this code, had no idea it worked this way before...but anyway, I think the problem @estrattonbailey is seeing is because the element needs to actually perform the animation before it gets destroyed. So i.e. if your exit animation runs for 300ms, you'd need to do something weird like:

- Add root element, add a conditional child with `isVisible` true
- Set `isVisible` to `false` at 3800 ms
- Destroy the root element at 4000ms

That feels pretty weird. At this point, you may as well just have the conditionally rendered element and leave the root always rendered. But we also have to make sure this API can remain usable outside React, unless we want to significantly change code (we use it outside react in quite a few places, which admittedly is nice and I think we should continue to allow if possible). I'm not the right person to provide an elegant and correct solution probably lol...but just some info based on problems I've had in the past.

**Comment by estrattonbailey** [comment]
Oh yeah good call — seems like a fine approach to me. `RootSiblings` shouldn't care what's rendered there, so should work I think.

**Comment by mozzius** [comment]
That's extremely odd, exit animation works on Android and Reanimated *should* keep it displayed while animating out

**Comment by mozzius** [comment]
But yeah the old version faded out before unmounting so we can just use the same approach here. Not as neat but oh well

**Comment by mozzius** [comment]
Fixed by making sure the Animated component is not at the root

**Pull request merged**
