### PR TITLE
Use new palette values for main palette

### PR DESCRIPTION
**Pull request by estrattonbailey**
Only swaps colors that will be very obviously different alongside new components.

### CODE REVIEW

**Review by pfrazee — APPROVED** [review]
Yep that's nice

**Comment by haileyok** [comment]
im guessing this is not intended?

Screenshot 2024-01-19 at 1 28 25 AM

**Comment by estrattonbailey** [comment]
@haileyok hmmmm (oh geez I hope I'm not missing something obvious), does something look off there?

**Comment by haileyok** [comment]
@estrattonbailey i didn't look closely but I'm betting the scroll view and the scroll view content container styles don't match up. Likely that the view itself's background is still solid black.

**Pull request merged**
