### PR TITLE
[APP-836] Emoji picker for web

### LINKED ISSUE #1199: Add emojis on desktop
**Is your feature request related to a problem? Please describe.**

Emojis are used as selection criteria for feeds. I can't see how to add them to a post on desktop (Chrome on Mac). 

**Describe the solution you'd like**

A possibility to add emojis to my posts like on mobile. 

**Describe alternatives you've considered**

Copy&paste from existing posts.

### PR DESCRIPTION
**Pull request by ansh**
Closes #1199 
- [x] Add emoji mart package for emoji picker functionality
- [x] Make it accessible with a screen reader
- [x] Allow emoji to be inserted
- [x] Close picker when emoji is selected
- [x] Cache emoji assets for 1 yr (h/t @Jacob2161)
- [x] Load emoji assets separate from main bundle

### CODE REVIEW

**Comment by pfrazee** [comment]
LGTM, one tweak I made is to use an icon instead of an emoji in the UI

CleanShot 2023-08-23 at 13 47 17@2x

**Review by pfrazee — APPROVED** [review]

**Comment by estrattonbailey** [comment]
Weird issue in Firefox, unsure what we can do here

https://github.com/bluesky-social/social-app/assets/4732330/69459eee-f300-4cb5-882a-de1275f8a518

**Comment by estrattonbailey** [comment]
Nit: can we make this text/emoji smaller so that it matches the rest of the modal?
Screen Shot 2023-08-23 at 5 35 20 PM

**Comment by estrattonbailey** [comment]
Also oddly can't scroll in the emoji window right now 🤔

**Review by pfrazee — APPROVED** [review]
🚀 😄

**Pull request merged**
