### PR TITLE
Fix: Some display issues

### PR DESCRIPTION
**Pull request by Hima-Zinn**
(English ver. by BIng Translation)
cf： https://github.com/bluesky-social/social-app/pull/2209#issuecomment-1857940070 ( @tkusano )

Dear Administrators of this Repository,
Hello.

When I was working on Japanese localization ( https://github.com/bluesky-social/social-app/pull/2209#issue-2040986838 ), a colleague discovered a problem that the GUI display was distorted in the early version of Japanese and that "Profile" was not displayed in Japanese.

With this fix, "NewPost" and "Profile" will be displayed correctly in the selected language, and other languages will be served more smoothly.

I hope you will join us in Merge.
Hima

(Original (Japanese))
関連： https://github.com/bluesky-social/social-app/pull/2209#issuecomment-1857940070 ( @tkusano )

このリポジトリの管理者のみなさん
こんにちは。

日本語のローカライズ作業をしていた（ https://github.com/bluesky-social/social-app/pull/2209#issue-2040986838 ）際、日本語の初期バージョンでGUIの表示が乱れ、また"Profile"が日本語で表示されない問題を仲間が発見してくれました。

この修正により、"NewPost"と"Profile"が選択した言語で正しく表示されるようになり、また他の言語の提供もスムーズになると思われます。

ぜひ、Mergeしていただければ幸いです。
Hima

### CODE REVIEW

**Comment by tkusano** [comment]
I propose a CSS fix to correctly display the translated versions of the  `Feedback · Privacy · Terms · Help` links in the desktop right navigation.
Without this patch, each link is word-wrapped in Japanese and looks ugly.

**Before patch:**
image

**After this patch applied:**
image

```diff
diff --git a/src/view/shell/desktop/RightNav.tsx b/src/view/shell/desktop/RightNav.tsx
index c126935d..8d9961a5 100644
--- a/src/view/shell/desktop/RightNav.tsx
+++ b/src/view/shell/desktop/RightNav.tsx
@@ -52,7 +52,7 @@ export function DesktopRightNav() {
               </Text>
             </View>
           ) : undefined}
-          <View style={[s.flexRow]}>
+          <View style={[{flexWrap: 'wrap'}, s.flexRow]}>
             {hasSession && (
               <>
                 <TextLink
```

**Comment by Hima-Zinn** [comment]
Thank you very much.
I will work on incorporating those corrections as well, so please be patient.

**Comment by Hima-Zinn** [comment]
@tkusano 
I have corrected the points you have pointed out.
Please check it.

In addition, since the content handled is now general display systems, I will change the title to an appropriate one.

**Comment by Hima-Zinn** [comment]
@ansh 
Since this issue is combined with the recent correction of the Japanese translation ( https://github.com/bluesky-social/social-app/pull/2209 ), I would appreciate it if you could MERGE both of them at the same time.

**Comment by ansh** [comment]
This looks good. Thank you @Hima-Zinn

**Review by tkusano — COMMENTED** [review]
checked

**Review by ansh — APPROVED** [review]
Changes look good to me.

**Pull request merged**
