### PR TITLE
Specify package manager in package.json

### PR DESCRIPTION
**Pull request by mozzius**
I'm not sure if it's yarn or node, but something keep trying to add this field automatically. I think its probably good to have anyway, so why not.

### CODE REVIEW

**Review by haileyok — APPROVED** [review]

**Comment by haileyok** [comment]
@mozzius Does this warn you if your yarn version is out of date?

**Comment by mozzius** [comment]
PNPM does, I'm unsure if Yarn will

**Comment by mozzius** [comment]
Ah yeah pretty sure it will

**Comment by hichemfantar** [comment]
corepack adds this field automatically. corepack is like a `package manager` manager

**Pull request merged**
