### PR TITLE
Upgrade Reanimated from 2.14.4 to 3.1.0

### LINKED ISSUE #751: Upgrade Reanimated from 2.14.4 to 3.1.0
**Is your feature request related to a problem? Please describe.**

Currently, Bluesky app uses Reanimated v2. As there's an update to v3, bumping to the major version should be considered, as there's no changes between both APIs. After bumping the version on local environment, an app works as usual.

**Describe the solution you'd like**

I'd prefer to update the version of Reanimated from v2 to v3 for better stability and support. It also fixes a problem with using legacy implementation on Drawer - see #585.

### PR DESCRIPTION
**Pull request by tboba**
## Summary 
Right now, Bluesky app uses Reanimated of version 2.14.4. This PR introduces an update for this library to 3.1.0 version.
It also removes the need to use `useLegacyImplementation` in drawer, introduced in PR #585, as in Reanimated version 3.1.0 drawer works properly on Android without using old implementation.

Fixes #751.

## Test plan
1. Run the AT Protocol server and mobile app using dev environment.
2. Create new account using launched locally AT Proto server as the hosting provider.

### Testing modals
As react-native-bottom-sheet uses react-native-reanimated behind the hood, it's worth testing if it still works on newer version of Reanimated.

3. Create a post with any content.
4. Try to repost it and then delete it.
Bottom sheet should work as usual.

https://github.com/bluesky-social/social-app/assets/23281839/30e9b7f6-9926-4a35-b7e9-a3bbf9a384c8

### Testing drawer
As this PR removes using `useLegacyImplementation`, it's worth testing if drawer works without this feature.

3. From the homepage open the drawer.
4. Try to open most of the options, available from it.
5. Try to close the drawer.

https://github.com/bluesky-social/social-app/assets/23281839/e06b8057-7676-4bdf-9e57-b4d957552f09

### CODE REVIEW

**Comment by piaskowyk** [comment]
Hey! 👋 As a Reanimated library maintainer I recommend upgrading 3.x version 😃

**Comment by ansh** [comment]
Thanks for opening this PR! The main issue with the drawer was that the gesture crashed the app on Android. I do not see the gesture to open drawer being tested in the video, so will test it out. But, thanks for opening this PR!

**Comment by tboba** [comment]
Hi @ansh, thanks for reaching out! You're right, I didn't recorded the moment of opening the drawer by gesture. After a quick check, it should work with current changes ✅ 

https://github.com/bluesky-social/social-app/assets/23281839/34b26ac6-6102-4210-9d90-9966ea3a8259

**Comment by ansh** [comment]
Thanks for the video! @tboba 

A few things blocking this PR are:
- Tests are failing (see Github action)
- Need to wait and test with changes in #777 since this PR might unfix that fix (weird, I know, but that's what I got when I tried)

**Comment by tboba** [comment]
> Tests are failing (see Github action)

Hmm, that's strange 🤔 but I see why they passed for me locally at first - it looks like patch-package is not adding `package.json` by default. It may just exclude all files that are not being put to `src` package 😅 

Anyways, I think they should work now (I hope 🤞).

**Comment by tboba** [comment]
Hi @ansh, is it possible to approve awaiting workflows at the moment? I just wanna check if tests are passing correctly 😁

**Comment by ansh** [comment]
@tboba Looks like everything is passing! I just need to test it on Android to make sure the modal isn't broken #777

**Comment by pfrazee** [comment]
Okay so @ansh this is blocked due to a bug with bottom-sheet & animated v3?

**Comment by ansh** [comment]
@pfrazee That is correct.

**Comment by tboba** [comment]
Hi @ansh, I'll give it a try! I've tried to update Reanimated to 3.2.0 before, but there was a problem with an undefined `_INJECT` prop, so I was waiting for the 3.3.0 release 😃 

Also, the tests should work without a newly added patch, I'll check that 👍

**Review by pfrazee — APPROVED** [review]
Simulator tests look good!

**Pull request merged**
