### PR TITLE
Update Korean localization

### PR DESCRIPTION
**Pull request by quiple**
Fixed some existing translations and translated newly updated strings from version 1.63.

Thanks!

### CODE REVIEW

**Comment by HaruChanHeart** [comment]
I just checked the translation, and there's no big problem, but I think we need a better translation here.

It looks better to say `피드 끝에 도달했습니다!`  as  `마지막 피드까지 도착했습니다!` 

If you want, I can review it and help you with the translation.

**Comment by quiple** [comment]
> I just checked the translation, and there's no big problem, but I think we need a better translation here.
> 
> It looks better to say `피드 끝에 도달했습니다!` as `마지막 피드까지 도착했습니다!`
> 
> If you want, I can review it and help you with the translation.

I think replacing "피드 끝" with "마지막 피드" seems undesirable because it completely changes the meaning (피드가 마지막인 것이 아니기 때문에), and "도달" and "도착" are practically synonymous and don't seem to make much difference, so I don't see the need to change them.

And best of all, that part is not currently marked for translation in version 1.63, so I don't think it matters much at this point. I'm just adding it for when it's later marked for translation.

Thanks!

**Comment by HaruChanHeart** [comment]
> I think replacing "피드 끝" with "마지막 피드" seems undesirable because it completely changes the meaning (피드가 마지막인 것이 아니기 때문에), and "도달" and "도착" are practically synonymous and don't seem to make much difference, so I don't see the need to change them.
> 
> And best of all, that part is not currently marked for translation in version 1.63, so I don't think it matters much at this point. I'm just adding it for when it's later marked for translation.

Thanks for commenting! I have a few more questions.

I think the sentence `이 도메인에 레코드가 추가됩니다` is explained in a confusing way. It seems meaning "This domain will add these records" (이 도메인에 다음 레코드들이 추가됩니다).

So, `도메인 레코드들을 다음과 같이 추가해 주십시오` seems more appropriate.

 ```po
 #: src/view/screens/Settings.tsx:803
msgid "Verify email"
msgstr "이메일 확인"
 
 #: src/view/screens/Settings.tsx:842
msgid "Protect your account by verifying your email."
msgstr "이메일을 인증하여 계정을 보호하세요."
 ```

And `이메일 확인` is would be better to change it to `이메일 인증` for unification with other sentences.

**Comment by quiple** [comment]
> Thanks for commenting! I have a few more questions.
> 
> I think the sentence `이 도메인에 레코드가 추가됩니다` is explained in a confusing way. It seems meaning "This domain will add these records" (이 도메인에 다음 레코드들이 추가됩니다).
> 
> So, `도메인 레코드들을 다음과 같이 추가해 주십시오` seems more appropriate.
> 
> ```po
> #: src/view/screens/Settings.tsx:803
> msgid "Verify email"
> msgstr "이메일 확인"
> 
> #: src/view/screens/Settings.tsx:842
> msgid "Protect your account by verifying your email."
> msgstr "이메일을 인증하여 계정을 보호하세요."
> ```
> 
> And `이메일 확인` is would be better to change it to `이메일 인증` for unification with other sentences.

Thanks for the review! I've updated all the `확인` related to email verification to `인증`.

And the sentence `이 도메인에 레코드가 추가됩니다` is not a description of the DNS record, but rather a description of the domain to which the record will be added.

This will localized as:

스크린샷 2024-01-07 12 05 46

this:

스크린샷 2024-01-07 12 05 20

**Comment by HaruChanHeart** [comment]
> And the sentence 이 도메인에 레코드가 추가됩니다 is not a description of the DNS record, but rather a description of the domain to which the record will be added.

Aha, sorry for misunderstanding :(

Now it doesn't seem like a problem anymore! Thank you for translating 👍

**Review by ansh — APPROVED** [review]
Great stuff! @quiple and @HaruChanHeart

**Pull request merged**
