### PR TITLE
Fix feed switching crash

### PR DESCRIPTION
**Pull request by ansh**
When some custom feeds were offline, it caused a crash on device

CleanShot 2023-10-10 at 13 21 36@2x

CleanShot 2023-10-10 at 13 28 24@2x

### CODE REVIEW

**Review by pfrazee — APPROVED** [review]
Surprised this was an issue, good to merge

**Comment by gaearon** [comment]
how did this happen? does this mean one of `renderEmptyState` callbacks has a Hook call inside? the linter shouldn't allow that

**Comment by pfrazee** [comment]
@gaearon let's plan to have a call on this, I'm somewhat confused about how we're supposed to handle render-function parameters in the RN components

**Comment by gaearon** [comment]
tbh I really don't understand what this fix is doing

**Pull request merged**
