### PR TITLE
bskyweb: iterate on RSS format, based on feedback

### PR DESCRIPTION
**Pull request by bnewbold**
- `pubDate` in RFC 822 datetime syntax
- remove `author`, which is supposed to be an email address. we already include the handle in the title of the overall feed
- add `isPermaLink=false` to `<guid>`

Just to note publicly, a known issue with these RSS feeds is going to be that the number of elements varies. This is because we are fetching a fixed number from the API, then filtering out re-posts. For accounts which re-post a lot, this will result in few feed items. We *could* have bskyweb paginated the API until it has enough items, but I think the better solution in the long run would be adding a query param to the feed endpoint to filter out reposts. I opened an issue for that here: https://github.com/bluesky-social/atproto/issues/1984

A sample of what the RSS looks like:

```xml
<rss version="2.0">
<channel>
<description>Social networking technology created by Bluesky. Developer-focused account. Follow @bsky.app for general announcements! Docs: atproto.com Community: atproto.com/community Developer blog: https://atproto.com/blog</description>
<link>https://bsky.app/profile/atproto.com</link>
<title>@atproto.com - AT Protocol Developers</title>
<item>
<link>https://bsky.app/profile/atproto.com/post/3kftlbujmfk24</link>
<description>hey developers, we're excited for more people to see your custom feeds soon when we launch the public web interface! ahead of that, we want to ensure that your feeds will work smoothly to handle both logged-out users and a potential increase in traffic. read some details on expected behavior here:</description>
<pubDate>06 Dec 23 00:19 +0000</pubDate>
<guid isPermalink="false">at://did:plc:ewvi7nxzyoun6zhxrhs64oiz/app.bsky.feed.post/3kftlbujmfk24</guid>
</item>
<item>
<link>https://bsky.app/profile/atproto.com/post/3kfqkkjdkic2e</link>
<description>Check out the latest featured community project: Bridgy Fed by @snarfed.org! Bridgy Fed is a bridge between social networks that currently supports the IndieWeb and the Fediverse, with full Bluesky support coming soon. Read more: atproto.com/blog/feature...</description>
<pubDate>04 Dec 23 19:28 +0000</pubDate>
<guid isPermalink="false">at://did:plc:ewvi7nxzyoun6zhxrhs64oiz/app.bsky.feed.post/3kfqkkjdkic2e</guid>
</item>
<item>
<link>https://bsky.app/profile/atproto.com/post/3kfdph62zey2f</link>
<description>Developers, we'll be at Open Core Summit on Dec 6-7 in San Francisco! Stop by to say hi and pick up some swag. 👾 Here's a discount code generated by Open Core Summit for FOSS builders to meet us there: opensourcefrens opencoresummit.com</description>
<pubDate>29 Nov 23 16:51 +0000</pubDate>
<guid isPermalink="false">at://did:plc:ewvi7nxzyoun6zhxrhs64oiz/app.bsky.feed.post/3kfdph62zey2f</guid>
</item>
<item>
<link>https://bsky.app/profile/atproto.com/post/3kdrlslade72m</link>
<description>Reminder: This is a developer-focused account, so if you see us using technical speak here, that's why! We'll always make relevant info more accessible to all users, and if you haven't already, please follow @bsky.app for general announcements. 😊</description>
<pubDate>09 Nov 23 18:33 +0000</pubDate>
<guid isPermalink="false">at://did:plc:ewvi7nxzyoun6zhxrhs64oiz/app.bsky.feed.post/3kdrlslade72m</guid>
</item>
<item>
<link>https://bsky.app/profile/atproto.com/post/3kdow6fj6la2l</link>
<description>Devs: you might've already seen some chatter about migrating accounts to servers named after mushrooms... Read the technical details and how it might affect you here: github.com/bluesky-soci...</description>
<pubDate>08 Nov 23 17:01 +0000</pubDate>
<guid isPermalink="false">at://did:plc:ewvi7nxzyoun6zhxrhs64oiz/app.bsky.feed.post/3kdow6fj6la2l</guid>
</item>
<item>
<link>https://bsky.app/profile/atproto.com/post/3kdk7yc3pbz22</link>
<description>📝Just published a new dev blog post: One of the core principles of atproto is simple access to public data. A user’s data is stored in a repository, which can be efficiently exported all together as a CAR file (.car). This post describes how to export and parse a data repository.</description>
<pubDate>06 Nov 23 20:13 +0000</pubDate>
<guid isPermalink="false">at://did:plc:ewvi7nxzyoun6zhxrhs64oiz/app.bsky.feed.post/3kdk7yc3pbz22</guid>
</item>
<item>
<link>https://bsky.app/profile/atproto.com/post/3kd5uzahw5t2u</link>
<description>do you subscribe to the For You custom feed and have opinions to share? the third-party devs behind the feed are hosting a zoom for the next 4 hours to hear your thoughts! ⬇️</description>
<pubDate>01 Nov 23 22:25 +0000</pubDate>
<guid isPermalink="false">at://did:plc:ewvi7nxzyoun6zhxrhs64oiz/app.bsky.feed.post/3kd5uzahw5t2u</guid>
</item>
</channel>
</rss>
```

cc: @scripting

### CODE REVIEW

**Comment by pfrazee** [comment]
@bnewbold we should go ahead and merge this and I'll cherry-pick it into the 1.60 release

**Review by pfrazee — APPROVED** [review]

**Comment by scripting** [comment]
I just thought I should check the feed one more time before you ship it. 

1. XML is case-sensitive. isPermalink is not correct. `isPermaLink` is. Link to [spec](https://cyber.harvard.edu/rss/rss.html#ltguidgtSubelementOfLtitemgt). 

I checked that the date/time strings are valid RFC 822, they are, according to [ChatGPT](https://chat.openai.com/share/437c451b-d888-4ed0-810a-ccb856ea2b28).

**Comment by bnewbold** [comment]
Ah, good catch, have a hotfix for that here: https://github.com/bluesky-social/social-app/pull/2271

**Comment by scripting** [comment]
@bnewbold @pfrazee --

highly recommend using a full url in the `<link>` element. 

in general in feeds, addresses aren't relative. 

too many things break.

**Comment by bnewbold** [comment]
@scripting I have a patch out to do full URL. To be clear, the RSS links (in XML) are all fully-qualified URLs, it is the HTML header `<link>` (which points to the RSS XML) which is a relative path. In my opinion relative paths should be fully supported when working with URLs in HTML (as opposed to XML), but can be pragmatic/flexible if it causes issues for popular clients.

**Pull request merged**
