### PR TITLE
Support dark mode embeds

### LINKED ISSUE #5119: [Embeds] Dark/night theme
I'm testing Bluesky embeds, and unless I'm missing something, there doesn't seem to be any support for a 'dark' or 'night' theme:

image

This results in embeds looking quite garish when on pages with dark themes.

**Describe the solution you'd like**

Ideally I would like for embeds to respect the light/dark theme setting of the page/browser/system, like Twitter/X embeds do:

image

image

Bluesky's clients already have a good 'dim' theme that color values can be borrowed from for this.

### PR DESCRIPTION
**Pull request by tpaulshippy**
Resolves #5119 

## Purpose
Support dark mode when embedding posts on other sites.

## Approach
Detect the browser's preferred color scheme using javascript and swap out background and text colors accordingly.

## Testing
Ran locally.

I have to say, getting the bskyembed app to function in a local dev environment was not easy. I have written up [an issue](https://github.com/bluesky-social/social-app/issues/6844) with documentation of my hacky workaround.

## Screenshots/Video

https://github.com/user-attachments/assets/9105c321-0d00-42c1-8901-a613d981045b

### CODE REVIEW

**Comment by gaearon** [comment]
The border looks a bit weird to me, is it supposed to be so strong?

**Comment by tpaulshippy** [comment]
Good question. I did not touch the border style. Perhaps it needs a border color?

**Comment by tpaulshippy** [comment]
Made the border black. See my screenshots in the PR. How's that?

**Comment by gaearon** [comment]
I think we'd want to keep the border (and the horizontal separator — they should share the color) visible, but they need to be very subtle in the dark mode, just like they're currently very subtle in the light mode. Maybe we could try `#2e4052`, which matches the border in the app?

**Comment by tpaulshippy** [comment]
Updated. What do you think?

**Comment by tpaulshippy** [comment]
Closing in favor of https://github.com/bluesky-social/social-app/pull/6912

**Pull request closed without merging**
