### PR TITLE
Add alt text validation option to user preferences (supersedes #913)

### LINKED ISSUE #907: Users should be able to opt into making alt text required for posts
**Is your feature request related to a problem? Please describe.**

I like to add alt text to images when I post on social media, but sometimes it can be easy to forget to add it before posting.

One solution is to provide a way to retroactively add alt text as suggested in #659, however, it would be useful to have an accessibility toggle that a user can enable that turns not having alt text on an image into a validation error to make it easier to remember to add alt text

**Describe the solution you'd like**

The ideal solution in my opinion would involve two new components. Firstly, a user setting toggle to force Alt Text validation errors on empty. This could either be in a new accessibility settings menu or within the top level menu

Illustration of proposed options menu addition. A new accessibility section with option to require alt text

When the toggle is enabled, it would show a validation error alerting the user that they need to enter alt text as well as disable the send button until alt text is added

Illustration of proposed validation error. An error is displayed to the user, letting them know they need to add alt text to their image submission

**Describe alternatives you've considered**

There's a few alternative implementations that would be worth considering.

As mentioned above, another way to help alleviate the issue would be supporting #659 which would make the need to provide upfront validation a smaller concern

Alternatively, instead of providing the option as a user toggle, a more aggressive strategy would be to make alt text mandatory for all users. This may be a very aggressive stance, which is why the proposal is to add a user toggle

**Additional context**

I would be happy to discuss further or make any proposed changes as an external contribution. I already started a working implementation of the proposed feature but I figured creating an issue first would be the preferred course of action

### PR DESCRIPTION
**Pull request by pfrazee**
Supersedes #913. Closes #907 

Builds on the PR by updating the UI of the toggle

CleanShot 2023-06-27 at 10 05 53@2x

### CODE REVIEW

**Comment by ansh** [comment]
Error does not go away even if I add alt text. It will go way if I press post because all alt text is added, but it is confusing for the user.

CleanShot 2023-06-27 at 12 00 30@2x

**Comment by pfrazee** [comment]
Yeah agree. I got pulled into an unscheduled meeting that ate most of my day, and I need to start building the release so I'm going to come back to this tomorrow and try to get it into the next build.

**Comment by Emma-Fuller** [comment]
Probably worth noting that the same behavior occurs with the "Did you want to say anything?" error

firefox_VJh0XeeTmf

> Error does not go away even if I add alt text. It will go way if I press post because all alt text is added, but it is confusing for the user.
> CleanShot 2023-06-27 at 12 00 30@2x

**Comment by pfrazee** [comment]
@ansh okay I updated it to do that now, RFR

**Review by ansh — APPROVED** [review]
🚀

**Pull request merged**
