### PR TITLE
fix: support scroll to top on profile screen

### PR DESCRIPTION
**Pull request by kadikraman**
Fixes https://github.com/bluesky-social/social-app/issues/719

This follows the existing pattern used on the other tabs: we listen to the `onScreenSoftReset` event and scroll to top when it is fired.

The diff looks bigger than the actual change (due to the `forwardRef` indentation), the main thing was wrapping `ViewSelector` in a `forwardRef` and adding this:

```js
React.useImperativeHandle(ref, () => ({
  scrollToTop: () => {
    flatListRef.current?.scrollToOffset({offset: 0})
  },
}))
```

so it could be called from the `ProfileScreen` when a soft reset is triggered.

## Before
https://github.com/bluesky-social/social-app/assets/6534400/cece8847-2709-411a-86ce-f6101a05d487

## After
https://github.com/bluesky-social/social-app/assets/6534400/ae3fdd3c-ca30-4da7-80fe-32303b991449

### CODE REVIEW

**Comment by piotrski** [comment]
dee

**Comment by piotrski** [comment]
Instead of using `useImperativeHandle` to handle the scroll-to-top behavior, I suggest using the `useScrollToTop` hook from react-navigation. It's a more convenient option provided by the library. Check out the [documentation](https://reactnavigation.org/docs/use-scroll-to-top/) for more details.

**Comment by kadikraman** [comment]
@piotrski for sure, I thought the same, but it is not used for the other tabs (I think because they want to do other actions like refresh the feed as well as scroll to top), so it seemed better to use an existing pattern instead of introducing something new for one tab. For reference, here's [Search](https://github.com/bluesky-social/social-app/blob/main/src/view/screens/SearchMobile.tsx#L96), [Notifications](https://github.com/bluesky-social/social-app/blob/main/src/view/screens/Notifications.tsx#L53), [Home](https://github.com/bluesky-social/social-app/blob/main/src/view/screens/Home.tsx#L174).

**Comment by ansh** [comment]
Would be better to use the existing button we have for scrolling to top.

**Review by pfrazee — APPROVED** [review]
Yeah looks great. Well done, thank you!

**Pull request merged**
