### PR TITLE
Adds `preconnect` links to essencial external domains

### PR DESCRIPTION
**Pull request by EvandroLG**
This PR adds preconnect links to optimize performance by establishing early connections to the following third-party origins: `bsky.app`, `bsky.social`, and `bsky.network`. Potential saving of 280ms according to `Lighthouse`.

### CODE REVIEW

**Comment by gaearon** [comment]
Would you mind doing these as well? Thanks!

https://github.com/bluesky-social/social-app/tree/4a158104017e23d876efae8cadf017b9a2c4c77a/bskyweb/templates

**Comment by mary-ext** [comment]
wouldn't adding `bsky.app` be unnecessary since the app is hosted on that very same domain?

**Comment by EvandroLG** [comment]
Done, @gaearon ;)
@mary-ext, makes all sense. Thanks ;)

**Comment by gaearon** [comment]
I think you got a formatting change in there — mind omitting that?

**Review by gaearon — APPROVED** [review]

**Comment by gaearon** [comment]
wonderful, thank you.

**Pull request merged**
