### PR TITLE
Fix: Show setting header in web

### PR DESCRIPTION
**Pull request by rahulyadav5524**
Previously:
Screenshot 2023-12-30 at 2 48 21 PM

Now:

Screenshot 2024-01-07 at 7 56 36 PM

### CODE REVIEW

**Review by pfrazee — COMMENTED** [review]
There's a subtlety to how layouts currently work that this PR misses. This will get easier to work with after https://github.com/bluesky-social/social-app/pull/2126 merges, but at the moment in this PR you lose the ability to scroll the page on desktop unless the cursor is in the center column. If you can fix that using the same techniques in other pages I'm +1 to merge.

**Comment by rahulyadav5524** [comment]
Sure thing. I need to change it to `List` and render items using it.
P.S: Same thing should be done in moderation screen

**Comment by pfrazee** [comment]
I just noticed that myself about the moderation screen. Bleh.

The `<List>` isnt the move for this. Take a look at https://github.com/bluesky-social/social-app/pull/2424/commits/cd88a241235cc927094fb81389728dea7053cd86 where I just did this for a different screen

**Comment by rahulyadav5524** [comment]
Fixed it. Will create a separate PR to fixed the moderation screen

**Comment by pfrazee** [comment]
Wonderful! Much appreciated!

**Pull request merged**
