### PR TITLE
Tweak shared element animation to make it much smoother

### PR DESCRIPTION
**Pull request by mrousavy**
It always felt off to me, so I wanted to change it. lmk ur thoughts on this PR.

<table>
<tr>
<th>Before</th>
<th>After</th>

<tr>
<td>

https://github.com/user-attachments/assets/991013cd-68ad-4bd6-8d24-25f42fb11f56

</td>

<td>

https://github.com/user-attachments/assets/8d13a4ca-917c-4e2d-af11-df414f21801f

</td>
</tr>
<tr>
<td>

https://github.com/user-attachments/assets/5671fb47-1576-40d1-9db0-56790380c062

</td>

<td>

https://github.com/user-attachments/assets/0a19d2bb-33ba-4bf1-b7b9-ee4c8770418e

</td>
</tr>
</table>

sorry I'm a bit perfectionistic when it comes to animations.

### CODE REVIEW

**Comment by mrousavy** [comment]
cc @gaearon we talked in DMs about this - lmk if this is something you like or not

**Comment by gaearon** [comment]
Ah yes this looks nice. I'll check it locally in a few hours, currently investing Android perf

**Review by gaearon — APPROVED** [review]
yea this feels good to me. thank you!

**Comment by mrousavy** [comment]
thanks dan!

**Pull request merged**
